"""Fire and Life Safety package - the written deliverable.

Revision FS2, 10 September 2026.

The plan text is FS1 unchanged.  FS1 was issued inside the Works Management
package because that is where the generator happened to live, which was the
wrong home for it: this is not a works-management deliverable but a life-safety
design and operating document for the finished shelter, and it belongs with the
discipline packages.  FS2 is that move.  Not one finding, route, distance,
policy clause or verification item is different.

What FS2 ADDS is the drawings the plan always needed - F-101 and F-102, from
fs_sheets.py - and the route schedule they are drawn from, fs_data.py.

Nothing about detection, alarm, suppression or emergency lighting is invented
anywhere in this package.  None of it exists: it all follows the electrical
design, which the project does not contain.  That is finding FS-5.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DOCS = os.path.join(ROOT, "Documentation")

REV = "FS2"
REV_DATE = "10 September 2026"

HDR = """<!-- GENERATED by Fire and Life Safety/Scripts/fs_docs.py.  Do not edit
     this file; edit the generator and re-run fs_build_all.py. -->

# {title}
## Underground CBRN-hardened blast-resistant protective structure and sentry post — Pune, Maharashtra

**Fire and Life Safety package revision FS2** · 10 September 2026
**Geometry:** Architectural Rev F · Structural Phase 2 Rev A + M1 · **Services:** Drainage DR1 · HVAC HV1 · Schedule of Finishes FN1 · Structural CAD SC1
**Evidence classes:** `[C]` confirmed · `[D]` derived here · `[A]` assumed by this package ·
`[U]` unresolved · `[N]` not available — data required

> **RELOCATED AND DRAWN, 10 September 2026 — revision FS2** (master Part **H.18**).
> This plan was first issued as **FS1** in `WORKS MANAGEMENT/Documentation/`. That was
> the wrong home: it is not a works-management document but a **life-safety design and
> operating document for the finished shelter**, so it now lives in its own discipline
> package alongside Drainage, HVAC and Schedule of Finishes.
>
> **Nothing in the FS1 text has been altered or withdrawn on the move.** Every route,
> travel distance, decision rule, policy clause and verification item is word for word
> what FS1 said. What FS2 adds is the two escape plan drawings this plan should always
> have had — **`DXF/F-101`** (underground level) and **`DXF/F-102`** (entry level) — and
> the route schedule they are drawn from, `Schedules/FS_ESCAPE_ROUTE_SCHEDULE.csv`.
>
> **The drawings found one thing the text had not: FS-6 / FS-V7**, the six-metre
> unequipped climb out of each escape shaft. It is added to §5 and §8 rather than left
> to sit on a drawing the written plan disagrees with. **That is the only addition, and
> the drawings resolve none of the six findings.**

---
"""


def head(title):
    return HDR.format(title=title)


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text.rstrip() + "\n")
    return path


# ===========================================================================
def doc_fire():
    """FIRE_SAFETY_AND_EVACUATION_PLAN.md - revision FS2.

    Built entirely from the project record.  No detection, alarm, suppression
    or emergency-lighting system is invented, because none exists: they all
    follow the missing electrical design package, which is the project's
    largest recorded information gap.
    """
    o = [head("FIRE SAFETY AND EVACUATION PLAN  \u00b7  revision FS2")]
    o.append("""
## 0  The one fact that governs everything else

**This is a sealed shelter. It cannot be ventilated of smoke.**

| | |
|---|---|
| Internal volume | 20.800 \u00d7 5.000 \u00d7 3.200 = **332.8 m\u00b3** gross |
| Design air supply | **300 m\u00b3/h** (RC1 ruling, master A.3) |
| Air changes | **\u2248 0.9 per hour** |
| Occupants | **9**, for **96 h** |
| Smoke extract | **NONE — and there cannot be one.** Every opening in the envelope is a blast valve or a blast door; a smoke vent would be a hole in the protective boundary |

A building fire strategy assumes smoke can be got out. **Here it cannot.** In
**Mode 3 CLOSED** — all five blast valves shut, 48 h limit — the shelter has **zero**
air exchange, and opening a valve to clear smoke **breaks the protection the shelter
exists to provide.**

So the strategy is not the usual one. It is: **prevent, detect early, extinguish while
it is small — and if it cannot be extinguished, LEAVE, because you cannot wait it out.**

---

## 1  What the design already does well

**These are real strengths and none of them had been written down.**

**1.1 The largest fire load is already compartmented away from the occupants.**
The 15 kVA generator sits in **Bay 8**, behind **Blast Door 2** in the 400 mm wall
**W7** — and Bay 8 is separated from the occupied bays by **Bay 7, the stair shaft**.
Two barriers and a buffer between the fuel and the people.

**1.2 Bay 8 has its own air path that never touches the gas-tight envelope.**
Mode 5 runs **2 600 m\u00b3/h** through **BV-4 / BV-5** for generator combustion and
cooling, and the operating-mode schedule states it **"does NOT touch the gas-tight
envelope; bay 8 not pressurised"**. **A generator fire is therefore ventilated, and
ventilated away from the occupied zone** — the one part of this shelter that can be
cleared of smoke is the one part most likely to produce it.

**1.3 The two dead-end bays are exactly the two bays with escape shafts.**

| Bay | Position | Escape |
|---|---|---|
| **Bay 1** | west end, 600\u20133500 | **ESC 1** at (2 050, 2 050) |
| **Bay 8** | east end, 18400\u201321400 | **ESC 2** at (19 900, 2 050) |

Every other bay has **two directions of travel** along the 20.8 m spine. **No occupant
is ever in a dead end without a way up out of it.** Whether or not that was deliberate,
it is correct.

**1.4 Travel distances are short.** The longest travel to a route is about **14.6 m**,
from the west end of Bay 1 to the stair shaft — and ESC 1 is 1.5 m away in that same
bay. Nothing in this shelter is far from a way out.

---

## 2  Where the fire load actually is

| Bay | Load | Comment |
|---|---|---|
| **8** | **Generator, fuel system, exhaust** | **The largest by far.** `[N]` — the set, its fuel system, exhaust and acoustic treatment are **not specified and not priced** (R-8) |
| 5 | CBRN filter trains AHU-1 / AHU-2 | **ASZM-TEDA activated carbon.** Carbon beds self-heat; a filter fire is a known hazard in protected ventilation |
| 1 | Stores | Combustible stores load not scheduled anywhere `[N]` |
| 3 | Ops room, **EMP Zone 2 enclosure** 3.0 \u00d7 3.0 \u00d7 2.4 | Electronics and cabling |
| 4 | Berthing, 9 berths | Bedding and personal effects |
| all | **Cabling** | **No electrical design package exists** — the project's largest gap. No cable type, route, containment or fire-stopping is specified anywhere `[N]` |

---

## 3  Detection, alarm, suppression, emergency lighting

**NONE OF IT EXISTS. NOT ONE ITEM.**

There is no fire detection, no alarm, no emergency lighting, no extinguisher schedule
and no suppression of any kind anywhere in this project. **This is not an oversight in
this plan — it follows directly from the fact that no electrical design package exists**,
which the project already records as its largest single information gap.

**Nothing is invented here to fill it.** What the plan can do is say precisely what has
to be designed, and that is in \u00a76 and \u00a78.

**The 1 000 L tank in Bay 1 is the 96-hour potable supply. It is NOT a firefighting
water source.** 1 000 L for 9 people over 4 days is 27.8 L/person/day. **Using it to
fight a fire trades the shelter's endurance for its fire response**, and that trade
must be a conscious decision, not an improvisation.

---

## 4  EVACUATION PLAN

### 4.1  The three routes

| | Route | Geometry | Emerges at |
|---|---|---|---|
| **R1** | **PRIMARY — main stair** | Any bay \u2192 spine \u2192 **Blast Door 1** in W6 \u2192 **Bay 7 stair shaft** \u2192 **24 risers @ 170.8333, 3 flights of 8, 1 200 wide**, rise 4 100, floor (\u2212)6.100 \u2192 (\u2212)2.000 | **Headhouse** at (\u2212)2.000, then **12 risers @ 166.6667** up the covered stairwell to the entry door **1 000 \u00d7 2 100 at grade** |
| **R2** | **ESC 1** | **Bay 1**, 1 400 dia clear, 250 RC collar | Head **+0.150** |
| **R3** | **ESC 2** | **Bay 8**, 1 400 dia clear | Head **+0.700** |

**R1 is the only route that does not require climbing a shaft**, and it is the only one
usable by an injured or unconscious person. **R2 and R3 are escape shafts, not exits** —
treat them as the last resort they are.

### 4.2  Decision rule — where the fire is decides the route

| Fire in | Route | Why |
|---|---|---|
| **Bay 8, generator** | **R1** (main stair), or **R2** if the spine is smoke-logged | **Blast Door 2 in W7 SHUT.** Bay 8 is already separately ventilated. **R3 / ESC 2 is inside the fire compartment — do not use it** |
| **Bays 1\u20136, occupied zone** | **R1** if the route to Bay 7 is clear; otherwise **R2** from the west end, **R1 or R3** from the east | Bays 1\u20136 are **one smoke compartment** (see FS-2) |
| **Bay 7, stair shaft** | **R2 or R3** | The primary route is the fire. **Both blast doors shut** |
| **Headhouse or covered stairwell** | **R2 or R3** | R1's surface end is blocked. Both are outside the protective boundary and the stairwell is **declared expendable** |

### 4.3  Immediate actions

1. **Raise the alarm by voice.** There is no alarm system (\u00a73). In a 20.8 m shelter with
   9 occupants and permanently open 900 partition gaps, voice carries.
2. **Attack it only while it is small**, and only if the route behind you is clear.
3. **Shut the blast door between you and the fire** — Blast Door 1 (W6) or Blast Door 2
   (W7). They are the only real barriers in the shelter.
4. **Stop the generator** if the fire is in Bay 8 or of unknown origin.
5. **Evacuate by the route \u00a74.2 gives.** Do not pass the fire to reach a preferred route.
6. **Roll call: 9.** The occupancy is a confirmed project figure, so the count is
   unambiguous. **Muster point \u2014 NOT DEFINED, no site plan exists (open item D3).**

### 4.4  Who does it

**There is no fire team. With 9 occupants, everyone is the fire team.** No fire duty,
warden role or drill frequency is defined anywhere in the project `[N]`.

---

## 5  Six findings this plan is obliged to raise

**FS-1  W5 is designated "fire and gas-tight" and NO DOOR EXISTS IN IT ANYWHERE IN THE
PROJECT.** Master A.3 confirms W5 (200 thk, Bay 5/6) as a fire and gas-tight separation.
The finishes package records the same gap as **FN-U1 / D-05**. **A fire separation with
an unfilled opening in it is not a fire separation** — and the compartment it is meant
to protect contains the **activated-carbon filter trains**. The finishes schedule
carried this as a data gap; **a fire plan makes it a defect.**

**FS-2  Bays 1 to 6 are ONE smoke compartment, 20.8 m long.** The four **W8 partitions
are 110 mm and non-structural, with permanent 900 door gaps at Y 2500\u20133400 and no doors
scheduled in them.** Smoke starting in Bay 1 reaches Bay 6 unobstructed. **This is not a
criticism of the partitions** — they were never designed as fire barriers — but it means
**the only real fire barriers in the shelter are Blast Doors 1 and 2, and W5 if it is
ever given its door.**

**FS-3  ESC 2 is in the same bay as the generator.** Both facts are confirmed and
neither is wrong on its own. **The coupling has never been stated: the most likely fire
in the shelter denies one of its three escape routes.** That is precisely why \u00a74.2
routes a Bay 8 fire away from ESC 2.

**FS-4  A fire during Mode 3 CLOSED cannot be ventilated at all**, and clearing smoke
means opening a blast valve, which **breaks the protection the closed mode exists to
provide.** The operating-mode schedule sets a 48 h limit on Mode 3. **No rule exists
anywhere in the project for which of the two hazards takes precedence.** That decision
belongs to the client, and it should be made before it is needed rather than during.

**FS-5  Every active fire measure follows the missing electrical design.** Detection,
alarm, emergency lighting and any suppression cannot be specified until that package
exists. **The programme already places the electrical design as the largest gap; this
plan adds fire to the list of things waiting on it.**

**FS-6  No ladder, rung or fall-arrest is specified in either escape shaft, and both
are climbs of over six metres.** ESC 1 emerges at **(+0.150)** and ESC 2 at **(+0.700)**;
the floor is at **(−)6.100**. That is a **6.250 m** climb out of Bay 1 and a **6.800 m**
climb out of Bay 8 `[D]`, and **nothing anywhere in the project says how either climb is
made, by whom, or whether an injured person can make it at all** `[N]`.

> **THIS FINDING WAS RAISED BY THE DRAWINGS, NOT BY THIS TEXT.** FS1 had all three
> numbers — both head levels and the floor level — and never put them in the same
> picture. Drawing **F-102**'s vertical profile put them side by side and the gap was
> immediately obvious. It is recorded here so the plan and the drawings say the same
> thing, and it is **FS-V7**.

---

## 6  Policy

**FS-P1  Prevention carries the weight here, because ventilation cannot.** Ignition
sources in the occupied bays are controlled by housekeeping and by keeping the
combustible stores load in Bay 1 to what the 96 h mission needs.

**FS-P2  The generator is treated as the fire risk it is.** It runs in Mode 5 with
**Blast Door 2 shut**, so Bay 8 is a separate compartment on its own air path whenever
the largest fire load in the shelter is operating.

**FS-P3  Blast doors are the fire doors.** They are the only barriers that work. Shutting
the blast door between the occupants and a fire is the **first** structural action, not
the last.

**FS-P4  W5 gets its door, or its designation is withdrawn.** One or the other. A wall
recorded as a fire separation with a permanent hole in it is worse than a wall that
claims nothing (**FS-1**).

**FS-P5  ESC 2 is not an escape route from a generator fire.** \u00a74.2 is the rule.

**FS-P6  The 1 000 L tank is potable water, not firefighting water.** Any use against a
fire is a deliberate trade against the 96 h endurance and is the commander's call.

**FS-P7  No fire measure is assumed to be priced.** No detection, alarm, extinguisher or
emergency lighting item exists in the bill. Anything specified is an **addition** to it.

**FS-P8  Construction-phase fire safety is a separate regime** and is already covered by
**IS 13416**, which is in the project's code register for exactly this.

---

## 7  What this plan cannot say

| Not stated | Why |
|---|---|
| Detection, alarm, emergency lighting, suppression | **No electrical design package exists** — the project's largest gap. `[N]` |
| Extinguisher type, number, siting | Nothing scheduled anywhere `[N]` |
| Fire ratings of doors, finishes, surface spread of flame | Recorded as **DATA REQUIRED** by the finishes package (**FN-D2**) |
| Cable type, containment, fire-stopping | Follows the electrical gap `[N]` |
| Generator fuel type, quantity, storage | The set and its fuel system are **not specified and not priced** (**R-8**) `[N]` |
| Muster point, assembly area, fire service access | **No site plan** — open item **D3** |
| Fire drill frequency, warden duties | No operational regime exists in the project `[N]` |
| Codes beyond **NBC 2016 Part 4** and **IS 13416** | Only those two are in the register. A full fire strategy will need standards for extinguishers, detection and emergency lighting; **their numbers are not invented here** and must be added to the register `[N]` |

---

## 8  Verification items

| Item | What it is | Status |
|---|---|---|
| **FS-V1** | **W5 has no door.** The designated fire and gas-tight separation between the CBRN plant bay and the decon airlock cannot function. Same defect as **FN-U1 / D-05**, raised again here because a fire plan cannot ignore it | **OPEN — design required** |
| **FS-V2** | No fire detection, alarm, emergency lighting or suppression exists anywhere. Follows the missing electrical design | **OPEN — follows the electrical gap** |
| **FS-V3** | No rule exists for a fire during **Mode 3 CLOSED** — smoke cannot be cleared without breaking protection | **OPEN — client ruling** |
| **FS-V4** | Generator fuel type, quantity and storage arrangement are unspecified, so the Bay 8 fire load cannot be quantified | **OPEN — follows R-8** |
| **FS-V5** | No muster point or fire service access can be defined without the site plan | **OPEN — follows D3** |
| **FS-V6** | No extinguisher schedule, drill regime or fire duty exists | **OPEN — operational, client** |
| **FS-V7** | **No ladder, rung or fall-arrest in either escape shaft.** ESC 1 is a 6.250 m climb from the floor and ESC 2 is 6.800 m. Raised by drawing F-102 | **OPEN — design required** |

---

*Revision FS2, 10 September 2026. FS1 is recorded in master Part H.17 and this
relocation, with its drawings, in Part H.18. Every element named is taken from the
project record. **No detection, alarm, suppression, extinguisher, ladder or
emergency-lighting specification is invented, because the project contains none.**
Nothing here resolves FN-U1, D3, R-8 or the electrical design gap.*
""")
    write(os.path.join(DOCS, "FIRE_SAFETY_AND_EVACUATION_PLAN.md"), "\n".join(o))

# ===========================================================================
def main():
    os.makedirs(DOCS, exist_ok=True)
    doc_fire()
    print("fire safety and evacuation plan written")


if __name__ == "__main__":
    main()
