"""fs_schedules.py  --  the escape route schedule, as .csv and .md.

Written from fs_data.py, which computes every distance from the project's
confirmed geometry.  Nothing here is typed by hand, so the schedule, the
drawings and the written plan cannot disagree about a travel distance.
"""
import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import fs_data as F                                        # noqa: E402

OUT = os.path.abspath(os.path.join(HERE, "..", "Schedules"))

HEAD = ["ROUTE", "DESCRIPTION", "GEOMETRY", "TRAVEL m", "CLIMB m",
        "EMERGES AT", "EVIDENCE"]


def rows():
    return [list(r) for r in F.ROUTES]


def main():
    os.makedirs(OUT, exist_ok=True)
    p = os.path.join(OUT, "FS_ESCAPE_ROUTE_SCHEDULE.csv")
    with open(p, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(HEAD)
        for r in rows():
            w.writerow(r)

    m = os.path.join(OUT, "FS_ESCAPE_ROUTE_SCHEDULE.md")
    with open(m, "w", encoding="utf-8") as f:
        f.write("<!-- GENERATED by Fire and Life Safety/Scripts/"
                "fs_schedules.py. -->\n\n")
        f.write("# ESCAPE ROUTE SCHEDULE  ·  revision FS2\n")
        f.write("## Underground CBRN-hardened blast-resistant protective "
                "structure — Pune\n\n")
        f.write("Drawn on **F-101** and **F-102**. Every travel and climb "
                "figure is computed from the\nproject's confirmed geometry, "
                "not transcribed — see `Scripts/fs_data.py`.\n\n")
        f.write("| " + " | ".join(HEAD) + " |\n")
        f.write("|" + "---|" * len(HEAD) + "\n")
        for r in rows():
            f.write("| " + " | ".join(str(c).replace("|", "\\|")
                                      for c in r) + " |\n")
        f.write(f"\n**Spine length, internal:** {F.SPINE_LEN:.1f} m  ·  "
                f"**Longest travel to R1:** {F.TRAVEL_R1:.1f} m  ·  "
                f"**Entry level travel:** {F.TRAVEL_ENTRY:.1f} m\n\n")
        f.write("> **R1 is the only route that is a stair.** R2 and R3 are "
                "escape shafts, and no ladder,\n> rung or fall-arrest is "
                "specified in either one anywhere in the project — "
                "**FS-6 / FS-V7**.\n")
    print("escape route schedule written")


if __name__ == "__main__":
    main()
