"""Site and Concealment package - the written deliverable.

Revision CAM2, 10 September 2026.

The policy text is CAM1 unchanged.  CAM1 was issued inside the Works Management
package because that is where the generator happened to live, which was the
wrong home for it: concealing the finished installation is a site and security
matter for the operator, not a works-management deliverable.  CAM2 is that
move.  Not one measure, signature, policy clause or verification item is
different.

What CAM2 ADDS is C-101, the above-ground signature elevation - every element
that stands above finished grade, drawn to scale at its confirmed height, which
is the policy's central finding made visible.

WHAT CANNOT BE DRAWN, and is not: a concealment layout.  There is no site plan
in this project - master open item D3 - so no element's position on the ground
is known except relative to the box.  C-101 says so on its face and shows the
sentry post detached, at its confirmed height but at no fixed distance.
Nothing about nets, screens, paint schemes, thermal treatment or detection
criteria is invented anywhere in this package, because the project contains
none of it: bill item B-camo is tagged [N], note "no concealment".
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DOCS = os.path.join(ROOT, "Documentation")

REV = "CAM2"
REV_DATE = "10 September 2026"

HDR = """<!-- GENERATED by Site and Concealment/Scripts/cm_docs.py.  Do not edit
     this file; edit the generator and re-run cm_build_all.py. -->

# {title}
## Underground CBRN-hardened blast-resistant protective structure and sentry post — Pune, Maharashtra

**Site and Concealment package revision CAM2** · 10 September 2026
**Geometry:** Architectural Rev F · Structural Phase 2 Rev A + M1 · sentry post SP-B2 · **Cover:** burster slab BS1, laid to a 1:50 crossfall
**Evidence classes:** `[C]` confirmed · `[D]` derived here · `[A]` assumed by this package ·
`[U]` unresolved · `[N]` not available — data required

> **RELOCATED AND DRAWN, 10 September 2026 — revision CAM2** (master Part **H.18**).
> This policy was first issued as **CAM1** in `WORKS MANAGEMENT/Documentation/`. That
> was the wrong home: concealing the finished installation is a **site and security
> matter for the operator**, not a works-management deliverable, and it is now in its
> own package.
>
> **Nothing in the CAM1 text has been altered or withdrawn on the move.** Every
> measure, signature and policy clause is word for word what CAM1 said. What CAM2 adds
> is **`DXF/C-101`, the above-ground signature elevation** — every element standing
> above finished grade, drawn to scale at its confirmed height. It makes §2's finding
> visible and it resolves nothing.
>
> **The drawing found one thing the text had not: CAM-V5**, the generator air shaft
> SH-2, whose head level is recorded nowhere in the project. Drawing it to scale meant
> having to say how tall it is, and the project cannot. It is added to §5 rather than
> left to sit on a drawing the policy disagrees with. **That is the only addition.**
>
> **No concealment layout drawing exists or can be drawn.** There is no site plan in
> this project — master open item **D3** — so nothing's position on the ground is known
> except relative to the box. C-101 states that on its face.

---
"""


def head(title):
    return HDR.format(title=title)


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text.rstrip() + "\n")
    return path


# ===========================================================================
def doc_camouflage():
    """CAMOUFLAGE_AND_CONCEALMENT_POLICY.md - revision CAM2.

    Short by design.  Every element it names is taken from the project record;
    nothing about nets, paint, screening, thermal treatment or detection is
    invented, because the project contains none of it - bill item B-camo is
    tagged [N] with the note 'no concealment'.
    """
    o = [head("CAMOUFLAGE AND CONCEALMENT POLICY  \u00b7  revision CAM2")]
    o.append("""
## What this is, and what it is not

A **short policy** for concealing the structure, written from what the project
actually contains. It is **not** a camouflage specification: bill item **`B-camo`**
— *"Camouflage and concealment measures beyond the 300 topsoil / turf layer"* — is
tagged **`[N]`**, quantity *to be verified from final measurement*, note **"no
concealment"**. **No net, screen, paint scheme, thermal treatment or detection
criterion exists anywhere in this project, and none is invented here.**

Concealment requirements also depend on two questions the project has never
answered — **U2**, whether a direct hit is a requirement, and **U3**, the design
basis threat yield. Both are in master **K.1b** awaiting a client or military
ruling. **This policy therefore states what the design already achieves and what
it does not, and stops there.**

---

## 1  The concealment the design already provides

| Measure | Value | Class |
|---|---|---|
| Topsoil / turf over the whole buried roof | **300 mm**, 30.867 m\u00b3, the top layer of the 2 000 engineered cover. A.7.3 names its function as *"Concealment, erosion, sheds rain"* | `[C]` |
| Turf sourced from the site itself | **92.82 m\u00b3 stripped and stockpiled** at `E-01a` for re-use in the concealment layer — the re-laid surface is the surface that was there before | `[A]` |
| Finished grade | **crowned, falling 1:50 away** (A.4.3) — a natural-looking shed, not a flat platform | `[C]` |
| Berm against the headhouse and covered stairwell | **1.5:1 to +0.900** | `[C]` / quantity `[N]` |
| Surplus excavation | **1 113.937 m\u00b3 re-used on site** as engineered fill and crushed rubble (`E-08`) | `[D]` |
| Roof penetrations for drainage | **NONE.** No roof outlet, no downpipe, no rainwater pipe on the buried roof — D-001 note 1 | `[C]` |
| Burster slab | laid to a **1:50 crossfall (BS1)** so infiltration disperses at the berm toe **without a pipe** | `[C]` |

**Two of these matter more than the rest.** Re-using the site's own stripped turf
means the restored surface is not a different green from its surroundings, which is
what usually gives a buried structure away. And **because the cover is drained
without a single pipe**, there is no manhole, no gully and no outfall anywhere on
the roof to break the surface.

---

## 2  The signature inventory — what is above ground

**Every one of these is a confirmed element of the project.** Heights are from the
master's level schedule.

| Element | Above grade | Note |
|---|---|---|
| **Sentry post** | **+7.000** parapet | Two storeys, 4 000 \u00d7 5 000, \u2265 10 m clear of the excavation. **The tallest thing on the site by 4.5 m** |
| Covered entry stairwell | **+2.450** head | 6 800 \u00d7 2 000. Outside the protective boundary, **declared expendable** |
| Fresh-air shaft **SH-1** | **+1.500** gooseneck | 600 \u00d7 600, west of the box |
| **Headhouse** | **+0.900** roof top | 4 800 \u00d7 5 800, walls 400, roof 500, **no earth cover**. The largest above-ground mass |
| Escape shaft **ESC 2** | **+0.700** head | 1 400 dia clear, OD 1900 collar |
| Escape shaft **ESC 1** | **+0.150** head | As ESC 2 |
| Generator air shaft **SH-2** | serves BV-4 / BV-5 | 600 \u00d7 600, east of the box |
| Soak pit / soakaway covers | at grade | SK-01 and SK-02 RC cover slabs. **Positions not fixed — no site plan (D3)** |
| Sentry post spiral stair | external | 1 000 R, 250 dia pole |

### The finding this policy exists to state

**The shelter is concealed. The installation is not.**

The buried box under 2 m of graded, turfed cover is genuinely hard to see. But a
**7 m sentry post 10 m away**, a **4.8 \u00d7 5.8 m headhouse with no earth cover**, a
**2.45 m stairwell head** and a **1.5 m gooseneck** are not concealed by anything,
and nothing in the project asks them to be. Anyone reading the cover build-up as a
concealment measure should understand that it conceals **the roof**, not the site.

**This is a statement of fact about the design as recorded, not a criticism of it** —
the sentry post is a manned observation position and is *meant* to be seen, and the
headhouse is the entrance. But the distinction has never been written down, and a
concealment policy that did not say it would be misleading.

---

## 3  Policy

**CAM-P1  The turf is a continuous surface, not a patch.** The 300 topsoil / turf is
laid over the whole buried roof and merged into the surrounding ground at the berm
toe. Re-lay the stockpiled site turf; do not import a different species or a
different soil colour.

**CAM-P2  No new spoil heap.** All 1 113.937 m\u00b3 of surplus is re-used on site as
engineered fill and crushed rubble. **A spoil mound is a permanent signature that
outlasts the works**, and this project has already designed the surplus away.

**CAM-P3  The berm reads as ground, not as an engineered line.** 1.5:1 to +0.900 is
the structural requirement; the graded finish either side of it should not leave a
straight crest visible against the natural fall.

**CAM-P4  Shaft heads sit as low as their function allows.** ESC 1 at +0.150 and
ESC 2 at +0.700 are already low. **Nothing bright, galvanised or reflective is left
exposed on a shaft head, a cover or a gooseneck** — but note that no finish is
specified for any of them anywhere in the project (see \u00a74).

**CAM-P5  Construction is the exposed phase, and it cannot be hidden.** The works
open **1 539 m\u00b3 of excavation** to 6.8 m and run for the whole substructure period.
No concealment measure in this project applies during construction. If concealment
matters during the works it is a **programme and access** question, and it needs the
site plan the project does not have.

**CAM-P6  Thermal and acoustic signature is the generator, and it is unquantified.**
The 15 kVA set in Bay 8 rejects heat and exhausts through the SH-2 shaft. The HVAC
schedule records **"Heat rejection into bay 8 NOT STATED"** \u2014 `[N]`. **Do not assume
the exhaust is concealed; nothing has been designed to conceal it.**

**CAM-P7  Do not assume concealment is priced.** `B-camo` carries **no quantity and
no rate**. Anything beyond the turf layer is an addition to the bill, not a variation
within it.

---

## 4  What this policy cannot say, and why

| Not stated | Why |
|---|---|
| Any net, screen, paint or thermal treatment | **No specification exists in the project.** `B-camo` is `[N]`, note "no concealment" |
| Approach routes, track discipline, tree lines, sight lines | **There is no site plan** — open item **D3**. The berm volume, access route and hardstanding are all unmeasurable for the same reason |
| Detection ranges, sensor types, observation distances | Not stated anywhere. They depend on **U2** and **U3**, both open |
| The generator's thermal output | HVAC records it as **NOT STATED** `[N]` |
| Where the soak pit and soakaway covers sit | Position not fixed — **D3**, no site plan |

---

## 5  Verification items raised by this policy

**These are new and they are open.** Adding them is the point of writing the policy
down: the project had concealment in its scope and its bill without a single line
saying what it was.

| Item | What it is | Status |
|---|---|---|
| **CAM-V1** | `B-camo` has no scope, no quantity and no rate. Either concealment beyond the turf layer is required and must be specified and priced, or it is not required and the item should be struck | **OPEN** — client ruling |
| **CAM-V2** | The above-ground signature (sentry post +7.000, headhouse +0.900 with no cover, stairwell +2.450, gooseneck +1.500) is **not concealed and is not required to be** by anything in the project record. Confirm that is intended | **OPEN** — client ruling |
| **CAM-V3** | No finish, colour or reflectivity is specified for any shaft head, cover slab or gooseneck | **OPEN** — `[N]`, data required |
| **CAM-V4** | Concealment during construction is not addressed by any measure in this project, and cannot be until the site plan (**D3**) exists | **OPEN** — follows D3 |
| **CAM-V5** | **The generator air shaft SH-2 has no recorded head level anywhere in the project.** Its 600 × 600 size and its duty (BV-4 / BV-5) are confirmed; how far it stands above grade is not. It cannot be assessed as a signature until it is. **Raised by drawing C-101** | **OPEN** — `[N]`, data required |

---

*Revision CAM2, 10 September 2026. CAM1 is recorded in master Part H.16 and this
relocation, with its drawing, in Part H.18. Nothing in this policy resolves U2, U3 or
D3, and nothing in it invents a specification the project does not contain.*
""")
    write(os.path.join(DOCS, "CAMOUFLAGE_AND_CONCEALMENT_POLICY.md"), "\n".join(o))

# ===========================================================================
def main():
    os.makedirs(DOCS, exist_ok=True)
    doc_camouflage()
    print("camouflage and concealment policy written")


if __name__ == "__main__":
    main()
