"""
wm4_doc.py — render the WM4 narrative document from the priced bill.

Works Management package revision WM4.  Every figure quoted in the prose is
read from wm4_bill.py / wm4_build.py, so the document cannot drift away from
the bill it describes.

    python3 wm4_doc.py          (or let wm4_build.py call it)
"""

import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, HERE)

import wm4_bill as BL
import wm4_build as BD
from wm4_ssr_library import SSR, CEMENT_BAGS, ON_COST
from wm4_owner_compare import COMPARE

OUT = os.path.join(ROOT, "Cost", "WM4_BOQ_AND_COST_ESTIMATE_SSR.md")


def render():
    t = BL.totals()
    rows, base, sub_ssr, before_gst, gst = BD.recap_rows()
    n = lambda k: len([x for x in BL.BILL if x["tier"] == k])
    M = lambda x: "{:,.0f}".format(x)
    comp = [c for c in COMPARE if c[6]]
    ov = sum(c[3] * c[4] for c in comp)
    sv = sum(c[3] * c[6] for c in comp)
    return TEMPLATE.format(
        nP=n("P"), nA=n("A"), nX=n("X"), nN=n("N"), nlines=len(BL.BILL),
        vP=M(t["P"]), vA=M(t["A"]), base=M(base),
        ssr_heads=M(sub_ssr - base), own_heads=M(before_gst - sub_ssr),
        gst=M(gst), est=M(before_gst + gst), oncost="%.4f" % ON_COST,
        s25=(CEMENT_BAGS["M25"] - CEMENT_BAGS["M20"]) * 50 * 6 * ON_COST,
        s30=(CEMENT_BAGS["M30"] - CEMENT_BAGS["M25"]) * 50 * 6 * ON_COST,
        s35=(CEMENT_BAGS["M35"] - CEMENT_BAGS["M30"]) * 50 * 6 * ON_COST,
        pardi25="{:,}".format(SSR["26.19"]["completed"]),
        pardi35="{:,.2f}".format(BL.DERIVED["PARDI_M35"]),
        waist25="{:,}".format(SSR["26.26"]["completed"]),
        waist35="{:,.2f}".format(BL.DERIVED["WAIST_M35"]),
        bands=_bands(), ncomp=len(COMPARE), ncompable=len(comp),
        own=M(ov), ssrv=M(sv), diff=M(sv - ov),
        diffpct="{:+.1f}".format(100 * (sv - ov) / ov),
        top3=_top3(comp), openitems=_open())


def _bands():
    o = []
    for c in ("E-02.1", "E-02.2", "E-02.3", "E-02.4", "E-02.5", "E-02.6"):
        r = [x for x in BL.BILL if x["code"] == c][0]
        band = r["desc"].split(",")[0].strip()
        strata = "soil" if c in ("E-02.1", "E-02.2") else "Deccan basalt"
        o.append("| %s | %s | %s | %s | %s |"
                 % (band, strata, "{:,.2f}".format(r["qty"]), r["ssr"],
                    "{:,.2f}".format(r["rate"])))
    return "\n".join(o)


def _top3(comp):
    o = []
    for c in sorted(comp, key=lambda c: -(c[3] * (c[6] - c[4])))[:3]:
        o.append("* **%s** — %s %s at Rs %s against SSR Rs %s: **Rs %s**."
                 % (c[1], "{:,.2f}".format(c[3]), c[2],
                    "{:,.0f}".format(c[4]), "{:,.2f}".format(c[6]),
                    "{:,.0f}".format(c[3] * (c[6] - c[4]))))
    return "\n".join(o)


def _open():
    return "\n".join("| **%s** | %s |" % (r[0], r[1]) for r in BD.OPEN_ITEMS)


TEMPLATE = r"""<!-- GENERATED by WORKS MANAGEMENT/Scripts/wm4_doc.py.  Edit
     wm4_ssr_library.py (the rates) or wm4_bill.py (the mapping) and re-run
     wm4_build.py, rather than editing this file. -->

# BILL OF QUANTITIES AND DETAILED COST ESTIMATE — SSR 2022-23
## Underground CBRN-hardened blast-resistant protective structure and sentry post — Pune, Maharashtra

**Works Management package revision WM4** · 15 September 2026
**Geometry:** Architectural Rev F · Structural Phase 2 Rev A + M1
**Quantities:** WM1 (master H.10), **unchanged**
**Rates:** Government of Maharashtra PWD **State Schedule of Rates 2022-23**

> **WM4 CHANGES NO DESIGN VALUE AND NO QUANTITY.** It fills the rate column
> WM1 deliberately left empty. No dimension, load, bar, level, thickness,
> date or float moves. **The main staircase is untouched** — 24 risers,
> 170.8333 mm riser, 280 mm tread, 3 flights × 8, 4 100 mm total rise.

---

## Why this revision exists

WM1 measured the whole project — 90 items in 10 sections — and carried **no
rate anywhere in it**. That was deliberate, and the master says why (Part G):

> *Rates come from the MES SSR. No item number could be verified from the
> material available, and inventing one would put false authority on a document
> an executing engineer might rely on.*

The project owner has now supplied the schedule itself: **`SSR 22-23 MH (1).pdf`**,
624 pages, the Government of Maharashtra Public Works Department State Schedule
of Rates for 2022-23, approved by Government Circular RADASU-2022/PR.KR.12/
NIYOJAN-3 dated 25 July 2022 and effective from that date. Every item number can
now be verified, so the bill can be priced. That is all WM4 does.

---

## The result

| | Lines | Amount |
|---|---:|---:|
| Priced at a **published SSR item** | {nP} | ₹ {vP} |
| Priced on a **stated assumption** `[A]` | {nA} | ₹ {vA} |
| **Included** in another rate — measured, not payable twice | {nX} | — |
| **NOT PRICED** — no specification, or no SSR item | {nN} | — |
| **TOTAL OF ITEMS** | **{nlines}** | **₹ {base}** |

| Recapitulation | Amount |
|---|---:|
| Total of items, SSR completed rates, excluding GST | ₹ {base} |
| SSR recapitulation heads (asset insurance 1 %, labour insurance 1 %) | ₹ {ssr_heads} |
| Owner's provision heads (contingency, water and power, consultant, supervision, statutory) | ₹ {own_heads} |
| GST @ 18 % `[A]` | ₹ {gst} |
| **ESTIMATED COST — CIVIL WORKS** | **₹ {est}** |

**Read the exclusions before using that figure.** It does **not** contain the
blast doors, the exit hatches, the blast valves, the NBC collective protection
trains, the EMP Zone 2 enclosure, the standby generator, the sump pumps or the
commissioning tests. **None of those has an SSR item**, and none is invented
here. The owner's own bill prices them at about **₹ 1.05 crore** from vendor
figures; those are not schedule rates and WM4 does not adopt them.

---

## The three things the schedule itself settled

### 1. Overheads and profit are already in the rate — so they are not added again

The SSR General Notes are explicit:

> *For labour amenities and all other overhead charges, **10 % provision is
> considered in Rate Abstract**. In addition, **10 % provision for Contractor's
> Profit** is also considered separately.*
> *Labour Cess at **1 %** has been considered separately in Rate Abstracts.*

The owner's own estimate adds **10 % contractor's overhead and profit** on top
of its rates. Against SSR completed rates that would be a double count, and WM4
does not make it. The on-cost already inside every rate is
1.10 × 1.10 × 1.01 = **{oncost}**, and the same factor is what carries a
derived material difference into a derived rate.

### 2. Formwork is already in the concrete rate — so F-01 and F-02 are not payable

Every SSR concrete item reads *"including **steel centering, formwork**, cover
blocks ... **(excluding reinforcement and structural steel)**"*. So the
1 057.743 m² of formwork and the 104 m² of falsework stay in the bill as
measured control figures at **nil**, and reinforcement is billed separately at
SSR 26.33. The 14-day prop period on the pressure slab remains a **programme**
driver whether or not it is a payable item.

The same logic retires three other groups from the money column: the bricks,
cement and sand of the sentry masonry are inside SSR 27.05; the cement and
aggregate procurement volumes are inside every composite rate; and **item W-05
and item B-screed are the same protection screed measured twice**, once in m²
and once in m³ — 102.889 × 0.100 = 10.289. It is paid once.

### 3. A grade the schedule does not publish is derived by the schedule's own rule

The SSR publishes R.C.C. **pardi** (wall) and staircase **waist slab** only to
M-25. The shelter box is M-35. The SSR says what to do:

> *If higher Concrete grade is required for any specific work, the rate analysis
> of the same shall be derived by **adding difference in standard cement
> consumption** in relevant SSR item's rate and shall be got approved from the
> Superintending Engineer, PWD of concerned circle.*

Standard consumption, from the SSR's own table: M25 **7.50** bags/m³,
M30 **8.00**, M35 **8.25**. Cement at the SSR general rate ₹6 000/M.T.

**And the formula is checked against the schedule before it is trusted.** Where
the SSR *does* publish consecutive grades, the step it prints must equal what
the formula computes — and it does, in four separate item families:

| Step | Formula | What the SSR prints |
|---|---:|---|
| M20 → M25 | {s25:.2f} | 183 / 184 |
| M25 → M30 | {s30:.2f} | 183 / 184 |
| M30 → M35 | {s35:.2f} | 91 / 92 |

So the M-35 wall rate is ₹{pardi25} + ₹275 = **₹{pardi35}/m³**, and the
M-35 staircase rate ₹{waist25} + ₹275 = **₹{waist35}/m³**.

---

## The excavation, priced by depth band

The SSR General Notes carry an increase for building excavation below 3.0 m:
**3.0–4.5 m add 20 %**, **4.5–6.0 m add 30 %**, and *"depth beyond 6.0 m — extra
percent to be decided by concerned Superintending Engineer."*

The shelter goes to **(−)6.800**. So the bulk excavation is billed in six bands
rather than as one line, and the bands reproduce the WM1 quantities exactly:

| Band | Strata | m³ | SSR | Rate ₹/m³ |
|---|---|---:|---|---:|
{bands}

Soil 295.20 + 49.20 = **344.40**, against WM1 item E-02a's 344.4.
Rock 246.00 + 295.20 + 295.20 + 157.44 = **993.84**, against WM1 item E-02b's
993.84. Nothing is re-measured; the same volume is simply billed where the
schedule says it should be.

**The rock is broken, not blasted.** `WM_CONSTRUCTION_METHODOLOGY.md` and risk
`S-02` both say so: *"Rock is removed by HYDRAULIC BREAKER, not by blasting ...
controlled blasting would require a vibration regime the project has not
specified."* So **SSR 21.20**, the schedule's chiselling / wedging / line
drilling item at ₹1 307, governs — and the three blasting items **21.17, 21.18
and 21.19** at ₹869, ₹1 033 and ₹1 322 **do not apply to this project at all**.

**The last 800 mm is the one band the schedule refuses to fix.** 157.44 m³
between (−)6.000 and (−)6.800, plus the 9.477 m³ sump pit below it, fall past
the SSR's last defined band. WM4 does not invent a percentage. Those two lines
carry the 4.5–6.0 m band's +30 % as a **declared lower bound**, tagged `[A]`,
and the question is raised as open item **WM4-V1**. Every further 10 percentage
points is about ₹21 800 on the two lines together.

---

## What the SSR does not contain

Six things were searched for and are simply not in the schedule:

| | |
|---|---|
| **Waterstops** | 109.76 m measured. Searched for *waterstop*, *water stop*, *water bar* and *PVC water bar* across all 624 pages — **no item exists** |
| **Spiral stair** | No item. SSR 40.06, an SS 304 handrail at ₹1 220/m, is the only related item and cannot stand for a stair |
| **Turfing** | The SSR directs Parks and Gardens wing rates, which this project does not hold. The 300 topsoil layer itself *is* priced, at 21.36, because it re-uses the material stripped at E-01a |
| **Armoured vision panels** | Not a schedule item |
| **EMP and shielding** | Nothing in chapters 41–43, or anywhere else |
| **Blast doors, hatches, valves, NBC trains, generator** | Nothing |

The schedule answers this itself, in Section B of the General Notes:

> *The items for which rates are not included in State Schedule of Rates, the
> rates shall be approved by concerned Superintending Engineer, PWD.*

That is the route for all of them, and it is recorded as open item **WM4-V7**
rather than filled with a number.

---

## The owner's own bill, checked against the schedule

Master H.15 records of the owner's priced bill: *"No cost was re-estimated, no
rate was checked against a market or a schedule of rates."* WM4 is that check.
Their quantities and their rates are reproduced exactly as supplied and
**nothing in their bill is edited**.

Of {ncomp} lines, **{ncompable}** have an SSR item that can stand against them.
On those lines:

| | Amount |
|---|---:|
| Owner's rates | ₹ {own} |
| SSR 2022-23 | ₹ {ssrv} |
| **Difference** | **₹ {diff}  ({diffpct} %)** |

The gap is concentrated in three places, and each has a reason:

{top3}

R.C.C. wall casting is the largest because wall formwork is what makes the SSR
pardi item dear, and the owner's single blended concrete rate of ₹8 640 does not
distinguish a wall from a raft. Rock excavation is second because the owner's
₹850 blends murum and basalt into one figure and carries no depth increase.
Reinforcement is third: ₹78 000 against the SSR's ₹89 703 for TMT Fe-500 fixed
in position.

**None of this makes the owner's bill wrong.** A rate below schedule is a
commercial position, not an error. What WM4 supplies is the comparison that did
not exist, line by line, so the position can be taken knowingly.

---

## The deliverables

| File | What it is |
|---|---|
| `Cost/WM4_Underground_Shelter_BOQ_Cost_Estimate_SSR_2022-23.xlsx` | **The workbook** — 11 sheets: cover, priced bill, recapitulation, rate derivation, SSR rate library, exclusions, the double-count guard, the owner comparison, SSR general rates, open items, verification. Every amount is a live formula |
| `Cost/WM4_BOQ_PRICED_SSR_2022-23.csv` | The priced bill, {nlines} lines |
| `Cost/WM4_SSR_RATE_LIBRARY.csv` | Every SSR item used, in the schedule's own wording, with its printed page |
| `Cost/WM4_COST_SUMMARY.csv` | The recapitulation |
| `Cost/WM4_OWNER_BILL_VS_SSR.csv` | The owner's bill re-rated |
| `Cost/WM4_OPEN_ITEMS.csv` | The seven questions this exercise could not answer |
| `Cost/WM4_RATE_DERIVATION.txt` | Every derived rate with its arithmetic |
| `QAQC/WM4_SSR_VERIFICATION.txt` | 18 consistency checks, and the rate-extraction audit |

Everything is regenerated by `Scripts/wm4_build.py`, which reads
`wm4_ssr_library.py` (the rates) and `wm4_bill.py` (the mapping). Nothing is
typed into an output file by hand.

---

## Open items this revision raises

| Ref | What it is |
|---|---|
{openitems}

None of them is closed here and none is guessed. Each one names what would
close it.

---

## What was verified, and how

* **18 automated consistency checks, 18 pass.** They prove that every WM1 line
  split to reach two SSR items sums back to the WM1 quantity exactly — the
  excavation bands, the headhouse walls against its roof, the sentry beams
  across two levels, the painting split — and that the reinforcement net weight
  is exactly the WM1 order quantity divided by 1.05.
* **Every rate re-read from the PDF a second time**, against the raw text of
  the page it sits on. 30 of 33 matched first time; three were checked by hand
  and **two were corrected** (21.40 and 39.50). Neither correction touches a
  priced line.
* **All 203 workbook formulas evaluated** and the workbook's own arithmetic
  shown to reproduce the bill — `Scripts/wm4_verify_xlsx.py`.
* **The grade-uplift formula checked against the schedule's own published
  steps** in four item families before being used where the schedule stops.

### What was NOT verified

* **No analysis was run.** This is a rating exercise. No `.std` file was opened
  and no STAAD.Pro run took place.
* **The quantities were not re-checked.** They are WM1's, and WM1's own 65-check
  audit covers them.
* **No district cost index was applied.** The SSR is a state schedule and its
  circular gives each Superintending Engineer power to vary rates for local
  conditions. No Pune circle variation exists in this project — **WM4-V4**.
"""


def main():
    io.open(OUT, "w", encoding="utf-8").write(render())
    print("  %-64s %8d bytes" % (os.path.relpath(OUT, ROOT),
                                 os.path.getsize(OUT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
