"""
wm_docs.py — renders every Works Management document from wm_data / wm_content.

Underground CBRN-hardened blast-resistant protective structure + sentry post, Pune.
Works Management package revision WM1.

Writes, into WORKS MANAGEMENT/ :
    Underground_Shelter_WBS.md / .csv
    Underground_Shelter_BOQ.md / .csv
    Underground_Shelter_Resource_Plan.md / .csv
    Underground_Shelter_Procurement_Plan.md / .csv
    Underground_Shelter_QA_QC_Plan.md / .csv
    Underground_Shelter_Safety_Risk_Register.md / .csv
    Underground_Shelter_Codes_References.md / .csv
and, into Documentation/ :
    WM_PROJECT_COMPONENT_REGISTER.md
    WM_CONSTRUCTION_METHODOLOGY.md
    WM_SENTRY_POST_BRICK_MASONRY.md
    WM_PROGRESS_MONITORING.md
    WM_ASSUMPTIONS_AND_VERIFICATION_REGISTER.md
"""

import csv
import os

import wm_data as D
import wm_schedule as S
import wm_content as C
import wm_quantities as QT

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DOCS = os.path.join(ROOT, "Documentation")

HDR = """<!-- GENERATED by WORKS MANAGEMENT/Scripts/wm_docs.py.  Edit the source
     data in wm_data.py / wm_content.py and re-run wm_build_all.py. -->

# {title}
## Underground CBRN-hardened blast-resistant protective structure and sentry post — Pune, Maharashtra

**Works Management package revision {rev}** · {date}
**Geometry:** {geom} · **Services:** {svc}
**Evidence classes:** `[C]` confirmed · `[D]` derived here · `[A]` assumed by this package ·
`[U]` unresolved · `[N]` not available — data required

> **THE ONLY DESIGN CHANGE in this package is reference SP-B1: the sentry post walls
> are BRICK MASONRY, replacing the Rev F 200 mm RC ballistic infill panels.
> No other element of the project is changed.**

> **AMENDED 10 September 2026 for design revision SP-B2** (master **A.4.8**, Part
> **H.12**), which designs the **lintel L1** and the **wall tie detail** that SP-B1
> created a need for and this package recorded as not existing. **WM-V5 and WM-V11 are
> closed by it.** The amendment is to the WRITTEN RECORD ONLY — the lintel and tie
> paragraphs, the risk entry, the verification register and the gap list now state the
> designed values instead of saying no design exists. **NO QUANTITY, RATE, DURATION,
> DATE, FLOAT OR RESOURCE IN THIS PACKAGE CHANGED**, and bill item `SP-06` still
> measures the superseded provisional 200 × 150 lintel section: see
> `Documentation/WM_RECONCILIATION_REGISTER.md` §6. **WM-V3, WM-V6 and WM-V7 remain
> open.**

---
"""


def head(title):
    return HDR.format(title=title, rev=D.REV,
                      date=D.REV_DATE.strftime("%d %B %Y"),
                      geom=D.PROJECT["geometry_rev"],
                      svc=D.PROJECT["services_rev"])


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text.rstrip() + "\n")
    return path


def wcsv(path, header, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(header)
        for r in rows:
            w.writerow(r)
    return path


def esc(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


# ===========================================================================
def doc_wbs(tasks):
    roll = S.wbs_rollup(tasks)
    by = {}
    for t in sorted(tasks.values(), key=lambda x: x.uid):
        by.setdefault(t.wbs, []).append(t)
    names = dict(D.WBS)

    o = [head("WORK BREAKDOWN STRUCTURE")]
    o.append("""The WBS covers the complete project from mobilisation to handover: the main
underground shelter, the entry structures, the sentry post, all services, the
external works and the concealment works. It has three levels — fourteen level-1
work packages, sixty level-2 sub-packages and 279 level-3 activities of which
eighteen are milestones.

The WBS and the programme are the same data. Every activity code below appears in
`Underground_Shelter_Final_Works_Programme.xml` with the same identifier, the same
duration and the same logic, and every BOQ item is measured against one of these
work packages.

| | |
|---|---|
| Level-1 work packages | 14 |
| Level-2 sub-packages | %d |
| Level-3 activities | %d (of which %d milestones) |
| Logic links | %d |
| Duration | %d working days, %s to %s |

---

## WBS summary — level 1 and level 2
""" % (len([c for c, _ in D.WBS if "." in c]),
       len(tasks), sum(1 for t in tasks.values() if t.is_milestone),
       sum(len(t.preds) for t in tasks.values()),
       max(t.ef for t in tasks.values()) + 1,
       S.CAL.day(0).strftime("%d %b %Y"),
       S.CAL.day(max(t.ef for t in tasks.values())).strftime("%d %b %Y")))

    o.append("| WBS | Work package | Activities | Start | Finish | Working days |")
    o.append("|---|---|---:|---|---|---:|")
    for code, title in D.WBS:
        if code not in roll:
            continue
        es, ef = roll[code]
        n = len([t for t in tasks.values() if t.wbs == code or
                 t.wbs.startswith(code + ".")])
        ind = "" if "." not in code else "&nbsp;&nbsp;&nbsp;&nbsp;"
        bold = "**" if "." not in code else ""
        o.append("| %s%s%s | %s%s%s%s | %d | %s | %s | %d |"
                 % (bold, code, bold, ind, bold, esc(title), bold, n,
                    S.dstr(es), S.dstr(ef), ef - es + 1))

    o.append("\n---\n\n## Full WBS — every activity\n")
    for code, title in D.WBS:
        if "." not in code:
            o.append("\n### %s  %s\n" % (code, title))
            continue
        if code not in by:
            continue
        es, ef = roll[code]
        o.append("\n**%s  %s**  ·  %s to %s\n" % (code, title, S.dstr(es), S.dstr(ef)))
        o.append("| Activity | Description | Days | Start | Finish | Preds | TF | Resources |")
        o.append("|---|---|---:|---|---|---|---:|---|")
        for t in by[code]:
            preds = ", ".join("%s%s%s" % (p, "" if ty == "FS" else ty,
                                          ("%+d" % lg) if lg else "")
                              for p, ty, lg in t.preds)
            o.append("| `%s` | %s%s | %s | %s | %s | %s | %d | %s |"
                     % (t.id,
                        "**" + esc(t.name) + "**" if t.is_milestone or t.tf == 0
                        else esc(t.name),
                        "" if not t.note else "<br>*%s*" % esc(t.note),
                        "—" if t.is_milestone else t.dur,
                        S.dstr(t.es),
                        S.dstr(t.es) if t.is_milestone else S.dstr(t.ef),
                        preds or "—", t.tf, esc(t.res) or "—"))

    o.append("""
---

## WBS coding rules

1. **Level 1** is a work package that could be let as a separate sub-contract or
   reported on separately to the client.
2. **Level 2** groups activities that share a work face, a trade and a set of hold
   points.
3. **Level 3** is an activity that one gang can be instructed to do, that has a
   measurable quantity behind it, and that can be marked complete without
   ambiguity.
4. Milestones carry zero duration and no resource. They are reporting events, not
   work.
5. Hold points are activities in their own right (they consume time and require
   the Engineer's attendance) and are named `HOLD POINT:` so that they cannot be
   passed over silently.
6. Activity numbering follows the level-1 package: `A1xxx` pre-construction,
   `A2xxx` earthworks, `A3xxx` substructure, `A4xxx` pressure slab, `A5xxx` entry
   structures, `A6xxx` waterproofing, `A7xxx` cover, `A8xxx` sentry post, `A9xxx`
   mechanical and CBRN, `A10xxx` drainage, `A11xxx` electrical and EMP, `A12xxx`
   finishes, `A13xxx` external works, `A14xxx` testing and handover.

## Where this WBS departs from the supplied R0 schedule

The supplied `UG CBRN HDRND OPS ROOM MCS — R0` schedule was used as the starting
point and its project start date, six-day calendar and the practice of naming the
structural consultant's checks as separate activities have all been kept. The
structure itself was rebuilt, because the R0 schedule describes a different
building:

| R0 activity | Why it is not in this WBS |
|---|---|
""")
    for item, why in C.NOT_COMPONENTS:
        o.append("| %s | %s |" % (esc(item), esc(why)))
    o.append("""
The R0 schedule also contained no sentry post as an identifiable structure, no
escape shafts, no blast doors, no CBRN plant, no EMP works, no engineered cover
build-up, no burster slab, no camouflage or concealment works, no procurement
activities, no commissioning sequence and one milestone. All of those are project
scope and all of them are now in the WBS.
""")

    write(os.path.join(ROOT, "Underground_Shelter_WBS.md"), "\n".join(o))

    rows = []
    for code, title in D.WBS:
        if code not in roll:
            continue
        es, ef = roll[code]
        rows.append([code, "", title, "", S.dstr(es), S.dstr(ef), "", "", "",
                     "SUMMARY"])
        for t in by.get(code, []):
            preds = ",".join("%s%s%s" % (p, "" if ty == "FS" else ty,
                                         ("%+d" % lg) if lg else "")
                             for p, ty, lg in t.preds)
            rows.append([code, t.id, t.name, t.dur, S.dstr(t.es), S.dstr(t.ef),
                         preds, t.tf, t.res, t.note])
    wcsv(os.path.join(ROOT, "Underground_Shelter_WBS.csv"),
         ["WBS", "Activity", "Description", "Duration (wd)", "Start", "Finish",
          "Predecessors", "Total float (d)", "Resources", "Note"], rows)


# ===========================================================================
BOQ_SECTIONS = [
    ("A", "SITE PREPARATION AND EARTHWORKS", ["E-"]),
    ("B", "MAIN UNDERGROUND SHELTER — CONCRETE", ["C-"]),
    ("C", "REINFORCEMENT — ALL WORKS", ["R-"]),
    ("D", "FORMWORK AND FALSEWORK", ["F-"]),
    ("E", "ENGINEERED COVER, OVERBURDEN AND CONCEALMENT", ["B-"]),
    ("F", "WATERPROOFING", ["W-"]),
    ("G", "SENTRY POST — CONCRETE AND FRAME", ["SC-"]),
    ("H", "SENTRY POST — BRICK MASONRY AND FINISHES  (design change SP-B1)", ["SP-"]),
    ("I", "ELECTRICAL AND EMP INSTALLATION", ["EL-"]),
    ("J", "PRINCIPAL MATERIALS — PROCUREMENT VOLUMES", ["M-"]),
]


def doc_boq():
    o = [head("BILL OF QUANTITIES")]
    o.append("""This bill covers the entire project: the main underground shelter, the entry
headhouse and covered stairwell, the escape shafts, the engineered cover, the
sentry post with its **brick masonry walls**, the services, the external works and
the concealment works.

**Nothing here is fabricated.** Every quantity is either taken directly from an
existing project package, or derived from confirmed project geometry with the
arithmetic shown. The full derivation, including the source of every input, is in
`Schedules/BOQ_QUANTITY_DERIVATION.txt` — 800 lines of working that can be checked
line by line.

Where a quantity genuinely cannot be determined from the project record, the item
says **To be verified from final measurement** and the reason is stated. It is not
estimated and it is not omitted.

### Basis of measurement

* Measurement follows the IS 1200 series (Part 1 earthwork, Part 2 concrete,
  Part 3 brickwork, Part 5 formwork, Part 12 plastering). %s
* Concrete volumes for the shelter and entry structures are taken **verbatim** from
  `Structural CAD/Schedules/REINFORCEMENT_SUMMARY.md` (package SC1). Six of the
  eight lines were independently re-derived here and reproduce exactly; the main
  staircase and entry stairwell are composite figures accepted as they stand.
* Reinforcement for the shelter and entry structures is taken verbatim from the SC1
  bar bending schedule: **70.46 t** across 92 bar marks. SC1's own convention is
  kept — cut length is the sum of scheduled legs with **no bend deduction**, laps
  at 50 φ added, stock bar 12 000. Bend deductions to BS 8666 Table 3 are the
  fabricator's on the approved schedule.
* The sentry post has never been quantified anywhere in the project. Its concrete
  (**20.95 m³ M30**) and reinforcement (**1.97 t**, about 94 kg/m³ — a plausible
  density for a small ductile-detailed frame) are derived here from the confirmed
  arrangement in master Part F.4, for **tender and estimating only**.
* Rates are not included. Rates come from the MES Standard Schedule of Rates. %s

---

## Bill summary

| Section | Description | Items | Principal quantities |
|---|---|---:|---|""" % (C.MES_CAVEAT, C.MES_CAVEAT))

    Q = QT.Q
    hi = {
        "A": "1 338 m³ bulk excavation · 994 m³ in rock · 290 m³ backfill",
        "B": "388.7 m³ M35 · 17.3 m³ M15 blinding",
        "C": "77.33 t ordered (70.46 shelter · 1.97 sentry · 1.22 burster)",
        "D": "1 058 m² formwork · 104 m² of falsework deck at 3.200 m",
        "E": "205.8 m³ in six layers · 20.6 m³ M30 burster slab",
        "F": "532 m² tanking · 110 m waterstop",
        "G": "20.95 m³ M30 · 4 No. footings F1",
        "H": "**12.20 m³ brick masonry · 64.19 m² face · ~6 400 bricks**",
        "I": "All quantities to be verified — no electrical design exists",
        "J": "194 t cement · 829 t aggregate",
    }
    for sec, name, pref in BOQ_SECTIONS:
        n = len([k for k in Q if any(k.startswith(p) for p in pref)])
        o.append("| **%s** | %s | %d | %s |" % (sec, name, n, hi[sec]))

    o.append("\n---\n")
    for sec, name, pref in BOQ_SECTIONS:
        o.append("\n## Section %s — %s\n" % (sec, name))
        o.append("| Item | Description | Unit | Quantity | Class | Notes |")
        o.append("|---|---|---|---:|---|---|")
        for code, (desc, unit, qty, cls, note) in Q.items():
            if not any(code.startswith(p) for p in pref):
                continue
            if qty is None:
                q = "**To be verified from final measurement**"
            elif qty >= 1000:
                q = "{:,.0f}".format(qty)
            elif qty >= 10:
                q = "%.1f" % qty
            else:
                q = "%.2f" % qty
            o.append("| `%s` | %s | %s | %s | `%s` | %s |"
                     % (code, esc(desc), unit, q, cls, esc(note) or "—"))

    o.append("""
---

## Section H notes — the sentry post brick masonry (SP-B1)

The walls between the sentry post columns are **one-brick-thick masonry in modular
bricks to IS 1077 (190 × 90 × 90)**, built inside the confirmed 200 mm structural
zone. The residual 10 mm is taken up at the internal face and absorbed in the
plaster, so the confirmed 4000 × 5000 external envelope and the flush column faces
are both preserved. Brickwork is measured at its **actual 190 mm thickness**, as
IS 1200 (Part 3) requires — not at the 200 mm zone width.

| | Ground storey | First storey | Total |
|---|---:|---:|---:|
| Wall run between columns | 15.200 m | 15.200 m | — |
| Panel height | 2.600 m | 2.600 m | — |
| Gross face area | 39.52 m² | 39.52 m² | 79.04 m² |
| Openings deducted | 3.33 m² | 11.52 m² | 14.85 m² |
| **Net masonry face** | **36.19 m²** | **28.00 m²** | **64.19 m²** |
| **Volume at 190 thk** | **6.88 m³** | **5.32 m³** | **12.20 m³** |
| Bricks including 5 % breakage | — | — | **≈ 6 400 No.** |
| Cement for CM 1:6 | — | — | 14.5 bags |
| Sand | — | — | 3.0 m³ |

**Openings.** Ground storey: door D1 900 wide and window W1 1200 wide, both read
from Rev F drawing 3. First storey: eight armoured vision panels 1200 wide, two per
face on all four faces, plus door D1, read from Rev F drawing 4. Opening
**heights are not stated anywhere in the project**; 2100 for the door (the project
convention for every other door) and 1200 for the window and vision panels are
assumed for measurement and are flagged as verification items WM-V3.

**Lintels are a new requirement created by this change.** The RC infill panels did
not need them; brick masonry does. When this bill was measured no lintel design
existed, so item `SP-06` is a provisional 200 × 150 section for quantity only, classed
`[N]`.

> **Superseded by SP-B2, 10 September 2026 (master A.4.8, Part H.12).** Lintel **L1**
> is now designed — **190 × 150, M30 / Fe500, 2-T10 bottom, 2-T8 top, T6 links @ 150,
> bearing 200 each end**, one type over all eleven openings. Over the same 17.000 m run
> of lintel that is **0.485 m³** against `SP-06`'s **0.510 m³**. **`SP-06` is left as
> measured and is NOT re-measured here** — 26 litres of M30 changes nothing, and this
> bill is a preserved revision. The supersession is recorded in
> `Documentation/WM_RECONCILIATION_REGISTER.md` §6 so the next revision picks up L1,
> with its reinforcement, rather than a provisional section with none.

---

## Items that cannot be quantified — declared, not omitted

| Item | Why |
|---|---|
| Berm volume, site regrading, access route, hardstanding | No site plan or ground model exists in the project (Drainage DR1 open item D3) |
| Camouflage and concealment beyond the 300 topsoil layer | No concealment specification exists |
| Every electrical quantity | No electrical design package exists. The scope is confirmed; the design is not |
| Blast door leaves, frames and anchorage | Vendor items; master F.1 records them as NOT AVAILABLE |
| Blast valves ×5, sleeves and trimming | Sizes are on sheet S-06 and are not in master Part B |
| Service-entry plate at wall W2 | Plate size NOT AVAILABLE |
| Ventilation and CBRN duct penetrations | No penetration schedule exists |
| EMP Zone 2 shielded enclosure | Specification is `[N]` in FN1 (finish code W-04) |
| Armoured vision panels | Specification not in the project |
| Sentry post ground-floor slab on grade | Not designed — the member schedule lists S1 at the first floor and roof only |
| Sentry post lintel design | Does not exist. A consequence of SP-B1 |
| Finishes rates | FN1 specifies performance; the product is deliberately open, so areas can be measured but rates cannot |
| Sentry post window and vision-panel heights | Not stated on any drawing |
| Drainage runs PD-06, PD-11, PD-13, PD-14, PD-16 | Lengths not determinable without a site plan |

---

## Declared conservatisms

| Item | Effect |
|---|---|
| Mat measured gross, with no deduction for the 1.5 × 1.5 sump opening | +1.35 m³, SC1's convention, kept |
| Excavation faces taken vertical and unbenched, no batter volume added | Bulk excavation is a **lower bound** |
| Bulking on rock excavation not applied | Loose volumes for haulage will be 40–60 % greater |
| Reinforcement cut lengths with no bend deduction | Conservative by about 2 φ per 90° bend |
| Cement at 400 kg/m³ for M35 against the IS 456 Table 5 minimum of 340 | Trial mix to IS 10262 fixes the real content |
| Mortar fraction 23 % applied to a one-brick wall whose thickness carries no joint | Slightly over-measures mortar |

---

## Reconciliation with the project record

| Check | Result |
|---|---|
| Mat 600 = 22.000 × 6.200 × 0.600 | 81.84 against SC1's 81.8 — **agrees** |
| Pressure slab 900 net of the void and two shafts | 112.03 against SC1's 112.0 — **agrees** |
| Perimeter walls = (22.000 × 6.200 − 20.800 × 5.000) × 3.200 | 103.68 against SC1's 103.7 — **agrees** |
| Walls W6/W7 = 2 × 0.400 × 5.000 × 3.200 | 12.80 against SC1's 12.8 — **agrees** |
| Wall W5 = 0.200 × 5.000 × 3.200 | 3.20 against SC1's 3.2 — **agrees** |
| Headhouse walls + roof | 32.74 against SC1's 32.7 — **agrees** |
| Sentry post steel density, 1.97 t in 20.95 m³ | ≈ 94 kg/m³ — plausible for a ductile-detailed frame. A sanity check, not a design check |
| Engineered cover, six layers × their thicknesses | 2 000 mm total, reproducing master A.7.3 |
""")
    write(os.path.join(ROOT, "Underground_Shelter_BOQ.md"), "\n".join(o))

    rows = []
    for sec, name, pref in BOQ_SECTIONS:
        for code, (desc, unit, qty, cls, note) in Q.items():
            if any(code.startswith(p) for p in pref):
                rows.append([sec, name, code, desc, unit,
                             "" if qty is None else round(qty, 3),
                             "To be verified from final measurement"
                             if qty is None else "", cls, note])
    wcsv(os.path.join(ROOT, "Underground_Shelter_BOQ.csv"),
         ["Section", "Section name", "Item", "Description", "Unit", "Quantity",
          "Status", "Evidence class", "Notes"], rows)


# ===========================================================================
def doc_resources(tasks):
    used = {}
    for t in tasks.values():
        for r in [x.strip() for x in t.res.split(";") if x.strip()]:
            used.setdefault(r, []).append(t)

    o = [head("RESOURCE PLAN")]
    o.append("""The resource plan covers the whole project. It lists the resources that actually do
the work and nothing else — a plan padded with resources that never appear on the
programme is not a plan.

Every resource below is assigned to at least one activity in
`Underground_Shelter_Final_Works_Programme.xml`; there are **%d assignments across
%d resources**. Peak numbers are the maximum simultaneous requirement and the entry
says what drives that peak.

---

## Staff

| Resource | Establishment | Peak | Responsibility | Activities |
|---|---|---:|---|---:|""" % (sum(len(v) for v in used.values()), len(used)))
    for name, group, comp, peak, note in D.RESOURCES:
        if group != "Staff":
            continue
        o.append("| **%s** | %s | %d | %s | %d |"
                 % (esc(name), esc(comp), peak, esc(note), len(used.get(name, []))))

    o.append("""
The **structural consultant** attends the reinforcement hold points. That practice
is carried over from the supplied R0 schedule, where 'Structural Consultant
Checking' appears before each major pour, and it is retained because on a blast
structure the pre-pour inspection is the last moment at which a detailing error
can be corrected.

---

## Labour

| Resource | Gang composition | Peak gangs | What drives the peak | Activities |
|---|---|---:|---|---:|""")
    for name, group, comp, peak, note in D.RESOURCES:
        if group != "Labour":
            continue
        o.append("| **%s** | %s | %d | %s | %d |"
                 % (esc(name), esc(comp), peak, esc(note), len(used.get(name, []))))

    o.append("""
---

## Plant and equipment

| Resource | Type / capacity | Peak | What drives the peak | Activities |
|---|---|---:|---|---:|""")
    for name, group, comp, peak, note in D.RESOURCES:
        if group != "Plant":
            continue
        o.append("| **%s** | %s | %d | %s | %d |"
                 % (esc(name), esc(comp), peak, esc(note), len(used.get(name, []))))

    o.append("""
---

## Resources for the sentry post, including the brick masonry

The sentry post is an independent structure with 118 working days of float, which
makes it the natural place to absorb labour redeployment when the main works are
held up. Its resource requirement is modest and mostly sequential.

| Work | Resources | Quantity | Basis of the duration |
|---|---|---|---|
| Excavation for footings F1 | Excavator, rock breaker | 37 m³ | 4 days; the rock breaker is already on site and off the main excavation |
| Blinding and footings | Concrete gang, bar bender gang | 5.4 m³ M30, 1.16 m³ M15 | Small pours, one day each |
| Columns, plinth beam, beams and slabs | Bar bender gang, carpenter gang, concrete gang | 15.6 m³ M30 | Two storeys with a 7-day cure between them |
| **Brick masonry — ground storey** | **Mason gang ×3, unskilled gang, scaffolding** | **6.88 m³ / 36.19 m²** | **5 days at roughly 2.4 m² per mason-day for a 190 wall with openings** |
| **Brick masonry — first storey** | **Mason gang ×3, unskilled gang, scaffolding** | **5.32 m³ / 28.00 m²** | **4 days; more openings, so less masonry but more cutting and more scaffold** |
| Lintels | Bar bender gang, carpenter gang, concrete gang | 0.51 m³ provisional | 2 days per storey |
| Spiral stair | Welding set, crane, unskilled gang | 1 No., 1000 R | 6 days, fabricated off site |
| Plaster | Plasterer gang ×2, scaffolding | 125 m² internal, 97 m² external | 6 days each at about 10 m² per plasterer-day |
| Flooring | Mason gang | 33 m² | 4 days |
| Electrical | Electrician gang | To be verified | Chases cut, not hammered — this is why the electrical first fix follows the masonry hold point |
| Painting | Painter gang, scaffolding | 223 m² | 6 days |

**The masonry gang is three masons plus helpers.** At roughly 2.4 m² of finished
one-brick wall per mason-day — reduced from the flat-wall rate because both storeys
are short panels between columns with a high proportion of opening perimeter and
cut brick — three masons clear the ground storey in five days and the first storey
in four. This is `[A]` and must be re-tested against the appointed contractor's
own output.

---

## Peak resource periods

| Period | Peak demand | Why |
|---|---|---|
| Dec 2026 – Jan 2027 | 2 excavators, 2 rock breakers, 4 tippers | 994 m³ of basalt removed by breaker in 20 working days |
| Mar – May 2027 | 4 bar-bender gangs | 24.7 t of wall reinforcement at 150 spacing both curtains |
| May – Jun 2027 | 4 bar-bender gangs, 4 carpenter gangs | Pressure slab: 20.5 t of T25 and 104 m² of deck at 3.200 m |
| 25–26 Jun 2027 | 2 concrete gangs, concrete pump, 4 transit mixers | The 112 m³ continuous pressure slab pour |
| Mar – Apr 2027 | 3 mason gangs | Sentry post brick masonry, both storeys |
| Aug – Sep 2027 | Excavator, roller, plate compactors | The six-layer engineered cover, 206 m³ |
| Sep – Oct 2027 | Specialist subcontractors | EMP survey, blast door tests, gas-tightness test, CBRN commissioning |

## Resource assumptions

All output rates are `[A]`. They are consistent with normal Indian site practice
and were used to build the durations in the programme, but they are the first
thing that should be re-tested when a contractor is appointed. The quantities they
are applied to are `[C]` or `[D]` and are traceable; the rates are not.
""")
    write(os.path.join(ROOT, "Underground_Shelter_Resource_Plan.md"), "\n".join(o))

    rows = []
    for name, group, comp, peak, note in D.RESOURCES:
        acts = used.get(name, [])
        rows.append([group, name, comp, peak, len(acts), note,
                     ";".join(sorted(t.id for t in acts))])
    wcsv(os.path.join(ROOT, "Underground_Shelter_Resource_Plan.csv"),
         ["Group", "Resource", "Composition", "Peak", "No. of activities",
          "Driven by", "Activities"], rows)


# ===========================================================================
def doc_procurement(tasks):
    o = [head("PROCUREMENT PLAN")]
    o.append("""Procurement is programmed, not assumed. Every package below is tied to an activity
in the master programme, and every package is required **before** the activity that
installs it. The dates are computed from the programme, not typed in.

The governing fact of this project's procurement is that **the blast door cast-in
frames must be welded into the W6 and W7 reinforcement cages before those walls are
poured.** That single dependency puts a vendor lead time on the critical path chain
from day one and is why the blast door enquiry is the first procurement activity.

---

## Procurement schedule

| Ref | Package | Enquiry / order | Order by | Required on site | Float |
|---|---|---|---|---|---:|""")
    for ref, pkg, req, lead, needed, note in C.PROCUREMENT:
        aids = [a.strip() for a in lead.replace("/", ",").split(",")
                if a.strip().startswith("A")]
        if aids and aids[0] in tasks:
            t = tasks[aids[0]]
            order_by, fl = S.dstr(t.ef), "%d d" % t.tf
        else:
            order_by, fl = "—", "—"
        o.append("| `%s` | **%s** | %s | %s | %s | %s |"
                 % (ref, esc(pkg.split("—")[0].strip()), esc(lead), order_by,
                    esc(needed), fl))

    o.append("\n---\n\n## Package detail\n")
    for ref, pkg, req, lead, needed, note in C.PROCUREMENT:
        o.append("\n### `%s`  %s\n" % (ref, pkg))
        o.append("**Requirement.** %s\n" % req)
        o.append("**Programme.** Enquiry and order at %s; required on site by %s.\n"
                 % (lead, needed))
        o.append("**Note.** %s\n" % note)

    o.append("""
---

## Long-lead items and their lead times

| Package | Lead time | Ordered | Delivered | Needed | Float |
|---|---:|---|---|---|---:|""")
    for aid, label, need_id in [
        ("A1120", "Blast door cast-in frames", "A3105"),
        ("A1122", "Blast door leaves", "A5135"),
        ("A1135", "CBRN filter trains", "A9040"),
        ("A1145", "Blast valves and sleeves", "A9015"),
        ("A1155", "EMP Zone 2 enclosure", "A11030"),
        ("A1160", "Generator 15 kVA", "A9050"),
        ("A1165", "Armoured vision panels", "A8195"),
        ("A1170", "Submersible pumps", "A10020"),
        ("A1172", "Reinforcement 77.3 t", "A3040"),
        ("A1174", "Waterproofing system", "A3020"),
        ("A1176", "Modular bricks to IS 1077", "A8130"),
    ]:
        t, n = tasks[aid], tasks[need_id]
        o.append("| %s | %d d | %s | %s | %s (`%s`) | %d d |"
                 % (label, t.dur, S.dstr(t.es), S.dstr(t.ef), S.dstr(n.es),
                    need_id, n.es - t.ef - 1))

    o.append("""
All lead times are `[A]`. They are realistic for the item type but they are not
quoted times, and replacing them with quoted times at tender is the single most
valuable thing that can be done to de-risk this programme.

---

## Procurement of the sentry post brick masonry — design change SP-B1

| Item | Quantity | Specification | Programme |
|---|---|---|---|
| Modular burnt clay bricks | ≈ 6 400 No. | Class designation 10 to **IS 1077**, 190 × 90 × 90. Sampled to **IS 5454**, tested to **IS 3495** for compressive strength, water absorption, efflorescence and warpage | Source approval and testing at `A1176`, 20 days, before order |
| Cement for mortar | 14.5 bags | OPC 43 grade to **IS 269** | With the main cement order |
| Sand for mortar | 3.0 m³ | To **IS 2116** | With the main aggregate order |
| Sand for plaster | With plaster | To **IS 1542** | — |
| Lintel reinforcement and concrete | 0.51 m³ M30 provisional | Design does not yet exist | Must be designed before `A8135` |
| Wall ties to the columns | Not determined | Detail does not exist in the project | Must be designed before `A8135` |

The whole brick requirement is about 6 400 bricks — a single approved batch. That
is an advantage worth protecting: **the source is approved once and is not changed
without retesting**, because a mid-job change of brick source on a 64 m² job means
retesting for a quantity too small to justify it.

---

## Material control on site

* Cement and reinforcement stacked to **IS 4082**; cement off the ground, covered,
  and used in delivery order.
* Bricks stacked clear of the working area, in stacks not exceeding the height that
  IS 4082 recommends, and **thoroughly soaked before laying**.
* Every consignment of reinforcement, cement, aggregate and brick is logged in the
  material test register against its certificate before it is used.
* Aggregate stockpiles kept separate by size and free of contamination from the
  rock crushing operation, which is running on the same site for the cover rubble.

---

## Procurement risks

The four packages with no recovery available once late are the blast doors, the
CBRN filter trains, the blast valves and the EMP enclosure. They are managed by
**monitoring the vendor**, with monthly manufacturing progress reports, rather than
by planning to recover — because there is no recovery to plan.

One package cannot yet be procured at all: **the electrical installation**, because
no electrical design package exists. No enquiry can be issued until the design is
produced, and that date is computed from the programme and issued to the designer
at mobilisation rather than requested when the activity is due to start.
""")
    write(os.path.join(ROOT, "Underground_Shelter_Procurement_Plan.md"), "\n".join(o))

    rows = []
    for ref, pkg, req, lead, needed, note in C.PROCUREMENT:
        rows.append([ref, pkg, req, lead, needed, note])
    wcsv(os.path.join(ROOT, "Underground_Shelter_Procurement_Plan.csv"),
         ["Ref", "Package", "Requirement", "Lead activity", "Required by", "Note"],
         rows)


# ===========================================================================
def doc_qaqc(tasks):
    holds = [t for t in sorted(tasks.values(), key=lambda x: x.es)
             if t.name.startswith("HOLD POINT")]
    o = [head("QUALITY ASSURANCE AND QUALITY CONTROL PLAN")]
    o.append("""This plan covers the whole project — the underground shelter, the entry structures,
the sentry post including its **brick masonry walls**, the services, the external
works, and testing and commissioning.

It is built around **hold points**. A hold point is an activity in its own right in
the programme: it takes time, it requires the Engineer's attendance, and work does
not proceed past it. There are **%d hold points** in the programme, and they are
placed at the moments where an error becomes permanent — the formation before it is
covered, the tanking before it is buried, the reinforcement before it is cast in,
the masonry before it is plastered.

**Inspection types.** `HOLD` — work stops until released. `WITNESS` — the Engineer
is invited and work may proceed if attendance is waived. `TEST` — a measurement
against a stated acceptance criterion. `SURVEILLANCE` — ongoing observation.

---

## Hold points in the programme

| Hold | Activity | Description | Date | Float |
|---|---|---|---|---:|""" % len(holds))
    for i, t in enumerate(holds, 1):
        o.append("| `%s` | `%s` | %s | %s | %d d |"
                 % (t.note or "H-%02d" % i, t.id,
                    esc(t.name.replace("HOLD POINT: ", "")),
                    S.dstr(t.es), t.tf))

    o.append("""
---

## Inspection and test plan

| Ref | Work | Stage | Requirement | Reference | Type | Record |
|---|---|---|---|---|---|---|""")
    for ref, work, stage, req, refc, typ, rec in C.ITP:
        o.append("| `%s` | **%s** | %s | %s | %s | `%s` | %s |"
                 % (ref, esc(work), esc(stage), esc(req), esc(refc), typ, esc(rec)))

    o.append("""
---

## The five checks that matter most on this project

**1. The formation (`Q-03`, hold point `H-01`).** The hazard is not the basalt, it
is the red-bole and vesicular seams at the flow contacts. A single seam under the
mat produces the differential-support case that sizes the mat. Every seam is
over-excavated and replaced with M15, and the approval carries a seam map.

**2. The tanking before it is covered (`Q-20`, hold points `H-02`, `H-09`,
`H-10`).** The external tank is continuous — under the mat, up the walls, over the
roof. Once it is backfilled it can never be seen again, and the structure sits with
its roof 2 m below grade and a design water table at the roof level.

**3. Reinforcement at 150 spacing both curtains (`Q-09` to `Q-11`).** The 150 mm
maximum bar spacing is an **EMP requirement** and is stricter than IS 456. It is not
a strength requirement, which means a site engineer looking only at strength will
see no reason not to relax it. It must not be relaxed.

**4. Formwork striking (`Q-16`, IS 456 Cl. 11.3 Table 11).** Props to a slab
spanning over 4.5 m stay for **14 days**. The pressure slab spans 5.000 m clear.
Striking requires a signed permit; the 14 days are in the baseline programme and
are not available for compression.

**5. Sentry post masonry line, level and plumb (`Q-25`, hold points `H-15`,
`H-16`).** Checked at the end of each storey, before plaster. Plumb over the 2.600
storey height and joint thickness are the two measurements that decide whether the
plaster can be held to its stated thickness — and once plaster is on, neither can
be corrected.

---

## QA/QC for the sentry post brick masonry — design change SP-B1

The masonry brings a set of checks that the RC infill panels did not need. They are
listed together here so that they can be issued as a single inspection sheet.

| Check | Criterion | Reference | When |
|---|---|---|---|
| Brick source approval | Class 10, dimensional tolerance on 190 × 90 × 90 | IS 1077 | Before order |
| Brick compressive strength | ≥ 10 N/mm² average | IS 3495 (Part 1) | Before order, and per delivery lot |
| Water absorption | Within the IS 1077 limit for the class | IS 3495 (Part 2) | Before order |
| Efflorescence | Within the IS 1077 limit | IS 3495 (Part 3) | Before order |
| Warpage | Within the IS 1077 limit | IS 3495 (Part 4) | Before order |
| Sampling | Sample size and selection | IS 5454 | Each lot |
| Soaking before laying | Bricks thoroughly wet, not surface-damp | IS 2212 | Continuous |
| Mortar proportioning | CM 1:6 by **gauge box**, not by shovel | IS 2250 | Each batch |
| Mortar working time | Used within 30 minutes; never re-tempered | IS 2250 | Each batch |
| Sand for mortar | Grading and cleanliness | IS 2116 | Source and each delivery |
| Bond | English bond, one brick thick | IS 2212 | Continuous |
| Joint thickness | 10 mm nominal, fully filled bed, cross and vertical | IS 2212 | Every course |
| Lift height | Not more than 1 m above adjacent work in a day | IS 2212 | Daily |
| Level | Every fourth course | IS 2212 | Continuous |
| Plumb | Over the full 2.600 storey height | IS 2212 | End of each storey — **hold point** |
| Frame interface | Top course wedged and packed only after initial shrinkage | IS 1905 | Before plaster — **hold point** |
| Wall ties to the columns | At the specified spacing — **detail does not yet exist** | — | Before plaster |
| Openings | Position and dimension against the Rev F drawings | Rev F drawings 3 and 4 | Before lintels |
| Lintels | Approved design, section, reinforcement, 200 bearing each end | IS 456 — **design does not yet exist** | Before and after casting |
| Curing | Damp for at least 7 days | IS 2212 | After each storey |
| Chases for conduit | **Cut, not hammered**; not before the masonry has cured | IS 2212 | Electrical first fix |
| Plaster | Thickness, line, level, no hollowness on tapping, 7-day cure | IS 1661 | Each face |

---

## Records

| Record | Raised by | Held by |
|---|---|---|
| Setting-out record and independent check certificate | Surveyor | QA/QC Engineer |
| Formation approval certificate with seam map | Site Engineer (Civil) | QA/QC Engineer |
| Material test register — cement, aggregate, steel, brick | Storekeeper | QA/QC Engineer |
| Mill certificates and independent steel test reports | Storekeeper | QA/QC Engineer |
| Pre-pour reinforcement checklists, countersigned | Site Engineer (Civil) | QA/QC Engineer |
| Formwork release notes and striking permits | Site Engineer (Civil) | QA/QC Engineer |
| Pour cards — one per pour, with slump and cube references | Site Engineer (Civil) | QA/QC Engineer |
| Cube test certificates at 7 and 28 days | Laboratory | QA/QC Engineer |
| Curing register | Site Engineer (Civil) | QA/QC Engineer |
| Construction joint records with photographs of waterstops and EMP straps | Site Engineer (Civil) | QA/QC Engineer |
| Tanking inspection certificates with photographic record | QA/QC Engineer | QA/QC Engineer |
| Field density test sheets | Laboratory | QA/QC Engineer |
| Brick and mortar test reports | Laboratory | QA/QC Engineer |
| Masonry inspection records with measured plumb and joint thickness | QA/QC Engineer | QA/QC Engineer |
| Drainage, electrical, earthing and EMP test certificates | Specialist / Electrician | QA/QC Engineer |
| Commissioning reports — filter trains, generator, gas-tightness, integrated | Specialist subcontractor | Site Engineer (Services) |
| Non-conformance reports and their close-out | Anyone | QA/QC Engineer |

## Non-conformance

A non-conformance is raised the moment it is identified, by anyone, and is closed
only by the QA/QC Engineer against evidence. Three categories of non-conformance on
this project are **not** closable by repair and require the designer's ruling:
reinforcement spacing relaxed beyond 150 in the protective envelope; a construction
joint formed without both waterstops and the EMP strap; and any penetration cut
through the envelope after casting.
""")
    write(os.path.join(ROOT, "Underground_Shelter_QA_QC_Plan.md"), "\n".join(o))

    wcsv(os.path.join(ROOT, "Underground_Shelter_QA_QC_Plan.csv"),
         ["Ref", "Work", "Stage", "Requirement", "Reference", "Type", "Record"],
         [list(r) for r in C.ITP])


# ===========================================================================
def doc_safety_risk():
    o = [head("SAFETY MANAGEMENT AND RISK REGISTER")]
    o.append("""## Part 1 — Safety management

The construction operation has four features that set its safety regime: a 6.8 m
deep excavation in rock, a buried structure that becomes a confined space,
substantial work at height on the headhouse and the sentry post, and specialist
lifting of heavy protective components.

**Baseline arrangements.** Site induction for every person before first entry.
Minimum PPE at all times: helmet, safety footwear, high-visibility clothing and eye
protection, with task-specific additions. A first-aid post and trained first-aiders
on site. A documented emergency plan that covers rescue from height, rescue from a
confined space and evacuation of a flooded excavation. A weekly safety walk and a
monthly safety committee. Permit-to-work for confined space entry, hot work and
live electrical work.

| Ref | Activity | Principal hazards | Controls | Reference |
|---|---|---|---|---|""")
    for ref, act, haz, ctrl, refc in C.SAFETY:
        o.append("| `%s` | **%s** | %s | %s | %s |"
                 % (ref, esc(act), esc(haz), esc(ctrl), esc(refc)))

    o.append("""
### Masonry-specific hazards — sentry post (`S-08`)

The brick masonry brings hazards the RC infill panels did not, and they are worth
setting out separately because masonry is often treated as a low-risk trade:

* **Falls from the masonry scaffold.** The first-storey panels are built 3.2 m
  above the ground floor. An independent tied scaffold with a proper working
  platform, guard-rail, mid-rail and toe-board is required — never a trestle
  standing on a slab edge.
* **Collapse of a freshly built panel.** A 190 mm panel 2.6 m high and up to 4.3 m
  long is slender while its mortar is green. Lift height is limited to 1 m above
  adjacent work in a day and free-standing panels are temporarily propped.
* **Manual handling.** About 6 400 bricks and 3.5 m³ of mortar are handled. Bricks
  are hoisted mechanically above ground level and never thrown.
* **Silica dust from cutting.** A high proportion of the masonry is short panels
  between columns with cut brick at every opening reveal. Wet cutting or on-tool
  extraction, plus respiratory protection.
* **Eye injury.** From mortar splash while laying overhead at the top course, and
  from chasing for electrical conduit. Eye protection for laying, cutting and
  chasing.
* **Wedging the top course.** Done from a proper platform, working overhead, after
  the panel has taken its initial shrinkage — a specific task with a specific
  method, not an afterthought.

### The three activities that would stop the job

1. **A fall of ground into the excavation** while people are working at (-)6.800.
   Controlled by designed faces, edge protection installed as the excavation
   deepens, and daily inspection after rain.
2. **A falsework collapse** during the 112 m³ continuous pressure slab pour, with
   a concrete gang working beneath 104 m² of deck at 3.200 m. Controlled by
   designed and checked falsework, inspected before every pour.
3. **A confined-space fatality** in the sump at (-)8.100 or in a 1400 mm escape
   shaft. Controlled by permit, gas testing, forced ventilation, harness and
   retrieval line, a standby person and a rehearsed rescue plan.

---

## Part 2 — Risk register

Risks are scored for likelihood (L) and impact (I) as H / M / L. The response is
what is actually done about it in the programme, the procurement plan or the
QA/QC plan — not a statement of intent.

| Ref | Category | Risk | L | I | Response | Owner |
|---|---|---|:-:|:-:|---|---|""")
    for ref, cat, risk, l, i, resp, owner in C.RISKS:
        o.append("| `%s` | %s | %s | **%s** | **%s** | %s | %s |"
                 % (ref, cat, esc(risk), l, i, esc(resp), owner))

    o.append("""
### The four risks that carry the project

**`R-04` Blast door frames arrive late.** The frames must be welded into the W6 and
W7 cages before those walls are poured. A late frame stops the wall, and the wall
stops the pressure slab, the cover and everything after it. This is the reason the
blast door enquiry is the first procurement activity on the programme.

**`R-08` No electrical design package exists.** The scope is confirmed — EMP Zone 2
enclosure, generator, earthing to 5 Ω, penetration protection — but no circuit,
cable, luminaire, distribution board or earth-electrode schedule does. Every
electrical quantity in the BOQ reads 'to be verified from final measurement'. This
is the largest single information gap on the project.

**`R-02` Red-bole seams under the mat.** The master is explicit that the hazard is
not the basalt but the flow contacts, and that a single seam produces the
differential-support case that sizes the mat. Confirmatory boreholes before
excavation, over-excavation and M15 replacement at formation, and a hold point that
carries a seam map.

**`R-01` Groundwater higher than the assumed (-)2.000.** Water is nearly two-thirds
of the 15.41 kPa/m lateral gradient. Monsoon monitoring is deliberately placed on
the critical path so that the answer arrives before the excavation support is
designed, not after the walls are built.

### Risks arising from the design change SP-B1

| Ref | Risk | Why it exists |
|---|---|---|
| `R-09` | No lintel design, no wall tie detail, and a changed seismic weight | The RC infill panels needed none of these; brick masonry needs all three. **The lintel and the tie detail are now designed — SP-B2, master A.4.8 / Part H.12. The changed seismic weight, WM-V6, is STILL OPEN** |
| `R-10` | Loss of the ballistic function the Rev F panels were named for | Brick masonry does not provide the protection that '200 RC ballistic infill' describes. Recorded so the decision is visible, not buried |
| `R-15` | Masonry workmanship — plumb, joint filling and the frame interface | A trade the project did not previously contain, on a structure with no other masonry |
| `R-16` | Brick supply consistency | Only about 6 400 bricks are needed, so one approved batch covers the job — but a mid-job source change would require retesting for a quantity too small to justify it |

The seismic point is worth stating precisely because it is easy to get wrong.
Master A.7.8 uses **R = 3.0 specifically because the infill is not separated from
the frame**, and B.8 designs to V<sub>b</sub> = 73.18 kN. Replacing 200 mm RC at
25 kN/m³ with 190 mm brickwork at about 20 kN/m³ reduces the infill line load from
13.000 kN/m to roughly 9.9 kN/m, which reduces the seismic weight and therefore
points the existing design in the **conservative** direction. That is a direction,
not a verification. The structural discipline must re-run the check. This package
does not, and does not claim to.
""")
    write(os.path.join(ROOT, "Underground_Shelter_Safety_Risk_Register.md"),
          "\n".join(o))

    wcsv(os.path.join(ROOT, "Underground_Shelter_Safety_Risk_Register.csv"),
         ["Type", "Ref", "Category / Activity", "Hazard / Risk", "L", "I",
          "Controls / Response", "Reference / Owner"],
         [["SAFETY", r[0], r[1], r[2], "", "", r[3], r[4]] for r in C.SAFETY] +
         [["RISK", r[0], r[1], r[2], r[3], r[4], r[5], r[6]] for r in C.RISKS])


# ===========================================================================
def doc_codes():
    o = [head("CODES, STANDARDS AND SPECIFICATIONS")]
    o.append("""Every reference in this register is a real, published document. **No IS clause
number, MES item number, SOR or SSR reference, specification number or document
title has been invented.**

Where a reference is carried over from master Part G it is marked `[C] master
Part G` — that register was compiled with the same rule and states that no clause
number in it was invented.

Where an exact reference could not be verified from the material available, the
entry says so in these words: *%s*

### How the register is used

* The **structural design** references govern what the structure is. They are the
  designer's, not the contractor's, and are reproduced here so that the Works
  Management documents cite the same authority as the design.
* The **construction, materials and workmanship** references govern how it is
  built and how it is accepted. These are the ones that appear in the inspection
  and test plan.
* The **measurement** references govern how the BOQ is measured and how the work
  is paid for.
* The **government** references — MES SSR, DWP, MESR, CPWD — govern the contract.
  Their existence is certain; their clause and item numbers are not, and none is
  quoted.

---
""" % C.MES_CAVEAT)

    groups = []
    for g, ref, title, use, cls in C.CODES:
        if g not in groups:
            groups.append(g)
    for g in groups:
        o.append("\n## %s\n" % g)
        o.append("| Reference | Title | Used for | Class |")
        o.append("|---|---|---|---|")
        for gg, ref, title, use, cls in C.CODES:
            if gg != g:
                continue
            o.append("| **%s** | %s | %s | `%s` |"
                     % (esc(ref), esc(title), esc(use), esc(cls)))

    o.append("""
---

## MES, CPWD and Service specifications — the honest position

The Military Engineer Services **Standard Schedule of Rates** and the **Defence
Works Procedure** are the documents that would actually govern a Service work of
this kind. They exist, they are named correctly above, and the work they would
govern is identified.

What is **not** given is any item number, clause number or rate. None could be
verified from the material available in this project, and inventing one would put a
false authority on a document that an examiner or an executing engineer might rely
on. Every such entry therefore carries the words:

> *%s*

The same applies to the CPWD Specifications and the Delhi Schedule of Rates. The
documents are real and the editions named are real; the individual item numbers are
not quoted because they are not verified.

---

## References that govern the design change SP-B1

The sentry post brick masonry is the only new construction type this package
introduces, so its references are collected here.

| Purpose | Reference |
|---|---|
| Brick specification | **IS 1077:1992** — common burnt clay building bricks; class designation 10, modular 190 × 90 × 90 |
| Brick testing | **IS 3495 (Parts 1 to 4):1992** — compressive strength, water absorption, efflorescence, warpage |
| Brick sampling | **IS 5454:1978** |
| Workmanship | **IS 2212:1991** — code of practice for brickwork |
| Masonry design | **IS 1905:1987** — structural use of unreinforced masonry |
| Mortar | **IS 2250:1981** — preparation and use of masonry mortars |
| Mortar sand | **IS 2116:1980** |
| Plaster sand | **IS 1542:1992** |
| Plaster application | **IS 1661:1972** |
| Painting | **IS 2395 (Part 1):1994** |
| Flooring | **IS 2571:1970** |
| Lintels | **IS 456:2000** — Cl. 22.2 effective span, Cl. 26.5.1.1 minimum tension steel, Cl. 26.5.1.6 nominal links, Table 19 shear. **Lintel L1 is designed to these clauses — SP-B2, master A.4.8** |
| Measurement | **IS 1200 (Part 3):1976** — brickwork, measured at the actual 190 thickness |
| Rates and specification clauses | MES SSR Part I and Part II. *%s* |

---

## Reference documents inside this project

These are not published standards, but they are the authority for everything this
Works Management package measures and schedules.

| Document | What it governs |
|---|---|
| `master/MASTER_PROJECT_STATE.md` | **The single source of truth.** Parts A, B, F and L are the authoritative current design |
| `master/QUICK_STATE.md` | Orientation digest only — never an authority |
| `Structural CAD/` package SC1 | Reinforcement package: 30 A1 drawings, 92 bar marks, 70.46 t, concrete volumes |
| `Drainage/` package DR1 | Drainage design basis, pipe, chamber, sump and pump schedules |
| `HVAC/` package HV1 | HVAC and CBRN design basis, equipment, duct, filter and damper schedules |
| `Schedule of Finishes/` package FN1 | Finish legend and rules for all thirteen spaces |
| `current/cad/` Rev F drawings | The ten architectural input drawings, including sentry post drawings 3, 4 and 6 |
| `current/staad/` | Underground plate model, sentry post frame model, entry stairwell frame model |
""" % (C.MES_CAVEAT, C.MES_CAVEAT))
    write(os.path.join(ROOT, "Underground_Shelter_Codes_References.md"), "\n".join(o))

    wcsv(os.path.join(ROOT, "Underground_Shelter_Codes_References.csv"),
         ["Group", "Reference", "Title", "Used for", "Class"],
         [list(r) for r in C.CODES])


# ===========================================================================
def doc_components():
    o = [head("PROJECT COMPONENT REGISTER")]
    o.append("""Before a work breakdown structure can be written, the components that make up the
finished project have to be identified from the project record — not assumed.

This register lists every component the current project documentation actually
establishes. A component is included only where the master project state file, the
Rev F drawings or an existing discipline package confirms it. Where the project
does not support a component, it is not invented, and the second table records the
items in the supplied R0 schedule that were removed for exactly that reason.

**Twenty-three components are confirmed. All twenty-three are covered by the Works
Management package.**

---

## Confirmed components

| Ref | Component | Description | Source | Class |
|---|---|---|---|---|""")
    for ref, comp, desc, src, cls, inscope in C.COMPONENTS:
        o.append("| `%s` | **%s** | %s | %s | `%s` |"
                 % (ref, esc(comp), esc(desc), esc(src), cls))

    o.append("""
---

## Components that do NOT exist in this project

The supplied R0 master construction schedule describes a different building in
several places. Each item below was removed from the Works Management scope because
the project record does not support it.

| Item in R0 | Why it is not in this project |
|---|---|""")
    for item, why in C.NOT_COMPONENTS:
        o.append("| **%s** | %s |" % (esc(item), esc(why)))

    o.append("""
---

## The three structures

The project is not one building. Master A.2 defines three separate structures, and
the Works Management package treats them as three, because they have different
design bases, different risk profiles and different places in the programme.

**1. The main underground box.** Buried RC shelter, eight bays, 22.0 × 6.2 m
external, roof 2.0 m below grade. Designed for a 344.7 kPa nuclear air-blast design
basis threat with a design pressure of 383 kPa on the roof **and** the walls. This
is the protected structure.

**2. The entry headhouse and covered approach stairwell.** Above-ground bermed RC
sitting on the shelter roof and on adjacent fill. The headhouse is designed for full
blast pressure on either face; **the covered stairwell is outside the protective
boundary and is declared expendable.**

**3. The sentry post.** A separate two-storey RC framed building at least 10 m clear
of the shelter excavation, on its own footings on in-situ rock. **Not blast
designed — a recorded decision.** Its walls are the subject of the only design
change in this package.

### The protective boundary

Master A.2 is explicit and the Works Management sequence depends on it:

> The protective boundary is **Blast Doors 1 and 2 at level (-)6.100, plus walls
> W6/W7, the perimeter walls, the mat and the pressure slab.** Everything above the
> blast doors — the stair shaft, the headhouse, the entry stairwell — is outside the
> boundary, and the entry stairwell is declared expendable.

That is why the blast door frames must be cast into W6 and W7, why there is no
movement joint anywhere inside the envelope, why every construction joint carries
two waterstops and a welded EMP strap, and why the gas-tightness test covers bays 1
to 6 only.

---

## Scope coverage check

| Requirement | Covered by | Where |
|---|---|---|
| Main underground shelter structure | `PC-01` to `PC-10` | WBS 3, 4 |
| Sentry post | `PC-19`, `PC-20` | WBS 8 |
| All associated structural works | `PC-11`, `PC-12` | WBS 5 |
| Access and egress | `PC-08` to `PC-12` | WBS 4.4, 5 |
| External works | `PC-21` | WBS 13 |
| Drainage | `PC-15` | WBS 10 |
| Waterproofing | `PC-14` | WBS 6 |
| Electrical works | `PC-17` | WBS 11 |
| Overburden and backfilling | `PC-13` | WBS 7 |
| Camouflage and concealment | `PC-22` | WBS 13.3 |
| Construction and completion activities | `PC-23` | WBS 1, 2, 14 |
""")
    write(os.path.join(DOCS, "WM_PROJECT_COMPONENT_REGISTER.md"), "\n".join(o))


# ===========================================================================
def doc_methodology():
    o = [head("CONSTRUCTION METHODOLOGY")]
    o.append("""This methodology describes how the complete project is built — the underground
shelter, the entry structures, the sentry post with its brick masonry walls, the
services, the cover and the external works — and why the sequence is what it is.

It is written to be read alongside the programme. Every section corresponds to a
level-1 work package, and the decisions explained here are the ones that produce the
logic links in `Underground_Shelter_Final_Works_Programme.xml`.

---
""")
    for ref, title, paras in C.METHODOLOGY:
        o.append("\n## %s  %s\n" % (ref, title))
        if ref == "M10":
            o.append("See `WM_SENTRY_POST_BRICK_MASONRY.md` — this is the only "
                     "design change carried by the Works Management package and it "
                     "has a document of its own.\n")
            continue
        for p in paras:
            o.append(p + "\n")

    o.append("""
---

## The construction sequence in one page

```
MOBILISE ─┬─ approvals, security clearance, site establishment
          ├─ survey, confirmatory SI, MONSOON GWT MONITORING  ← closes the
          │                                                     biggest assumption
          └─ ORDER BLAST DOORS  ← day one; the frames gate the walls

EARTHWORKS ─ clear, strip topsoil (keep it) ─ temporary works ─ excavate soil
           ─ break rock in two lifts ─ sump pit ─ dewater ─ trim formation
           ─ over-excavate red-bole seams ─ FORMATION HOLD POINT

SUBSTRUCTURE ─ blinding ─ TANKING (horizontal) ─ HOLD POINT ─ mat + sump in one
             pour ─ 14-day cure ─ wall steel ─ BLAST DOOR FRAMES welded to the
             cage ─ walls in two lifts ─ lower stair flights

PRESSURE SLAB ─ falsework 3.2 m ─ bottom steel ─ trimmers, collars, thickenings
              ─ links ─ top steel ─ haunches ─ cast-ins ─ HOLD POINT
              ─ 112 m3 CONTINUOUS POUR ─ 14-day cure ─ 14-day props (IS 456
              Table 11) ─ strike ─ upper stair flight

    then, in parallel:
      ENTRY STRUCTURES ─ headhouse walls and roof ─ covered stairwell ─ escape
                         shaft collars ─ blast doors installed
      WATERPROOFING ─ vertical tanking ─ HOLD POINT ─ roof membrane ─ protection
                      screed ─ HOLD POINT
      SENTRY POST ─ (starts only after the rock breaking) footings ─ frame
                    ─ BRICK MASONRY ground storey ─ HOLD POINT ─ first storey
                    ─ HOLD POINT ─ lintels ─ spiral stair ─ plaster ─ finishes
      SERVICES ─ builder's work with the RC ─ ductwork ─ blast valves ─ filter
                 trains ─ generator ─ drainage ─ EMP enclosure ─ electrical

COVER ─ side backfill in 250 layers, density tested ─ 100 screed ─ 750 fill
      ─ 500 crushed basalt from our own excavation ─ 200 M30 BURSTER SLAB
      ─ 150 filter ─ 300 topsoil and turf ─ verify against master A.7.3

EXTERNAL ─ berm 1.5:1 ─ regrade with 1:50 falls ─ access ─ turf ─ concealment
         ─ remove temporary works

TEST ─ cubes and NDT ─ watertightness ─ drainage ─ electrical ─ earth 5 ohm
     ─ EMP SURVEY 80 dB ─ blast door seals ─ GAS-TIGHTNESS ─ CBRN commissioning
     ─ generator ─ INTEGRATED PROTECTIVE MODE ─ snag ─ rectify ─ contingency
     ─ HANDOVER
```

---

## Two claims this methodology does not make

The master project state file is explicit that two things must never be claimed
about this structure, and they are not claimed here.

**A static analysis gives the demand, not proof of blast resistance.** The
non-linear SDOF support-rotation check is Phase 3 work and has not been done. The
construction methodology delivers the structure that was designed; it does not
validate the design.

**Flotation cannot be read off the model.** The springs take tension. It is a hand
check, and it is the designer's.

Separately, and specific to this package: **editing and verifying a `.std` file is
not running an analysis.** No STAAD.Pro run was made in producing this Works
Management package, and none is claimed.
""")
    write(os.path.join(DOCS, "WM_CONSTRUCTION_METHODOLOGY.md"), "\n".join(o))


# ===========================================================================
def doc_brick():
    B = C.BRICK_METHOD
    o = [head("SENTRY POST — BRICK MASONRY WALLS  ·  design change SP-B1")]
    o.append("""## The decision

%s

## What follows from it

%s

---

## Geometry and quantity

| Item | Value | Basis |
|---|---|---|""" % (B["decision"], B["consequence"]))
    for k, v, basis in B["geometry"]:
        o.append("| **%s** | %s | %s |" % (esc(k), esc(v), esc(basis)))

    o.append("""
### Why 190 mm and not 230 mm

The confirmed structural zone between the column faces is **200 mm** (master A.4.8:
external 4000 × 5000, internal 3600 × 4600, columns 350 × 350 with their outer faces
flush with the wall). Two standard Indian brick sizes are available:

* **Modular, IS 1077, 190 × 90 × 90** — builds a 190 mm one-brick wall, which fits
  inside the 200 mm zone with 10 mm to spare. The 10 mm is taken up at the internal
  face and absorbed in the plaster.
* **Conventional, 230 × 110 × 75** — builds a 230 mm wall, which would project 30 mm
  beyond the column faces and change the confirmed 4000 × 5000 external envelope.

The modular brick is adopted because it preserves every confirmed dimension. Using
the conventional brick would be a second design change, and the instruction for this
package is that there is only one.

### Why the panel height is 2.600 m

This is the project's **own confirmed figure**, not an assumption of this package.
Master A.7.7 gives the infill load on the first-floor beams as 13.000 kN/m and
verifies it as 0.200 × 2.600 × 25; Rev F drawing 6 repeats '200 × 2600 high'.

The first storey checks geometrically: roof slab top +6.700 less the 450 beam depth
gives a soffit at +6.250, and +6.250 − +3.650 = 2.600. **It agrees.**

The ground storey does not: first floor +3.650 less 450 gives a soffit at +3.200, and
+3.200 − +0.450 = **2.750**, which is 150 mm more than the project's own figure. The
confirmed 2.600 is used for both storeys and the 150 mm difference is carried as
verification item **WM-V1**. It is declared, not resolved.

---

## Construction method

""")
    for i, step in enumerate(B["method"], 1):
        parts = step.split(". ", 1)
        o.append("**%d. %s.** %s\n" % (i, parts[0], parts[1] if len(parts) > 1 else ""))

    o.append("""
---

## Programme

| Activity | Description | Days | Predecessor logic |
|---|---|---:|---|
| `A1176` | Modular bricks — source approval, testing and order | 20 | After the quality plan is approved; **before** any brick is delivered |
| `A8130` | Brick delivery, stacking, sampling and testing to IS 3495 | 4 | After `A1176` and after the first-floor slab is cast |
| `A8135` | **Brick masonry — ground storey** | 5 | After the first-floor slab has cured (`A8090`) so there is something to build up to |
| `A8140` | RC lintels — ground storey | 2 | After `A8135` |
| `A8145` | **HOLD POINT** — line, level, plumb, joint thickness | 1 | After `A8135` and `A8140` |
| `A8150` | **Brick masonry — first storey** | 4 | After the roof has cured (`A8120`) and the ground storey is signed off |
| `A8155` | RC lintels — first storey | 2 | After `A8150` |
| `A8160` | **HOLD POINT** — first storey inspection | 1 | After `A8150` and `A8155` |
| `A8165` | **MILESTONE** — sentry post brick masonry complete | 0 | — |
| `A8175` | Electrical conduits and boxes **chased** into the masonry | 4 | After the masonry hold point — chases are cut, never hammered, and never before curing |
| `A8180` | Internal plaster 12 mm sand faced, CM 1:4 | 6 | After the electrical first fix |
| `A8185` | External plaster 15 mm, two coat, with scaffolding | 6 | After the internal plaster |

Each storey is built only after the slab above it has cured, so the masonry is built
into a completed frame rather than the frame being completed around it. The
alternative — building the masonry as the frame rises — would put the panel under
load from the frame's own deflection, which is exactly what the wedging rule exists
to prevent.

---

## Bill of quantities extract

| Item | Description | Unit | Quantity |
|---|---|---|---:|
| `SP-01` | Brick masonry, ground storey, 190 thk in a 200 zone, CM 1:6, incl. scaffolding | m³ | 6.88 |
| `SP-02` | Brick masonry, first storey, 190 thk in a 200 zone, CM 1:6, incl. scaffolding | m³ | 5.32 |
| `SP-03` | Modular burnt clay bricks class 10 to IS 1077, incl. 5 % breakage | No. | 6 403 |
| `SP-04` | Cement for masonry mortar CM 1:6 | bag | 14.5 |
| `SP-05` | Sand for masonry mortar, to IS 2116 | m³ | 3.0 |
| `SP-06` | RC lintels over openings, 200 × 150 **provisional — design required** | m³ | 0.51 |
| `SP-07` | Internal cement plaster 12 mm, sand faced, CM 1:4 | m² | 125.2 |
| `SP-08` | External cement plaster 15 mm, two coat | m² | 97.4 |

---

## Verification items raised by this change

| Ref | Item | Status |
|---|---|---|
| `WM-V1` | Ground-storey panel height: the project's confirmed 2.600 against the 2.750 implied by +0.450 FFL and the +3.200 beam soffit | **OPEN** — 2.600 used |
| `WM-V2` | First-floor west wall: the D1 door at Y 1000–1900 lies inside the vision panel at Y 1000–2200 on the Rev F drawing | **OPEN** — the union is deducted once |
| `WM-V3` | Window W1 and vision-panel heights are not stated anywhere | **OPEN** — 1200 assumed for measurement |
| `WM-V4` | 190 mm modular brickwork inside the 200 mm zone needs the designer's confirmation | **OPEN** |
| `WM-V5` | Lintel design over D1, W1 and the eight vision panels does not exist | **CLOSED by SP-B2**, 10 Sep 2026 — lintel **L1**, 190 × 150, M30 / Fe500, 2-T10 bottom, 2-T8 top, T6 links @ 150, bearing 200, one type over all eleven openings. Master A.4.8 / Part H.12 |
| `WM-V6` | Seismic weight changes when RC infill becomes brickwork. Brick at ~20 kN/m³ over 0.190 × 2.600 gives ~9.9 kN/m against the confirmed 13.000 kN/m, so the existing V<sub>b</sub> = 73.18 kN is conservative — **but this is a structural matter and must be re-checked by that discipline** | **OPEN** — referred, not resolved |
| `WM-V7` | Ballistic performance. The Rev F panels are described as '200 RC BALLISTIC INFILL'; brick masonry does not provide equivalent ballistic protection | **OPEN** — recorded so the consequence of the instructed change is visible |
| `WM-V11` | Wall tie detail between the masonry and the columns | **CLOSED by SP-B2**, 10 Sep 2026 — 6 mm MS ties at every fifth course (≈ 450) up both column faces, 200 into the bed joint, 10 mm cast-in or drilled-and-grouted dowel. Master A.4.8 / Part H.12 |

**Two of these were closed after this package was issued.** WM-V5 and WM-V11 are closed
by design revision **SP-B2** (10 September 2026, master **A.4.8** and Part **H.12**),
which designs the lintel and the tie detail this document said did not exist. **The
lintel and tie paragraphs above have been updated to the designed values**; the SP-B1
planning assumptions they replaced — a provisional 200 × 150 section and ties at every
fourth course — are superseded and recorded as such.

**Everything else here is still open.** Master rule M.6 applies: an item that is
unresolved stays unresolved until the user supplies the answer. In particular
**WM-V3** (the opening heights are still not stated on any drawing) stays open on
purpose — L1 is designed to an arching bound that does not use a height, so it neither
needs nor confirms the 1200 assumed for measurement. **WM-V6** (the seismic re-check)
and **WM-V7** (the ballistic function) also stay open, and WM-V7 is a client decision
that no drafting or design work in this project can close.
""")
    write(os.path.join(DOCS, "WM_SENTRY_POST_BRICK_MASONRY.md"), "\n".join(o))


# ===========================================================================
def doc_progress(tasks):
    P = C.PROGRESS
    o = [head("PROGRESS MONITORING AND CONTROL")]
    o.append("## Baseline\n")
    for p in P["baseline"]:
        o.append(p + "\n")
    o.append("\n## Measurement of progress\n")
    for p in P["measurement"]:
        o.append(p + "\n")

    o.append("""
## Three reporting streams, one project

Progress is tracked separately for three streams and consolidated for the project.
The streams are chosen so that each has a different trade, a different work face and
a different risk profile — reporting them together would hide exactly the divergence
that matters.

| Stream | Scope | How it is measured |
|---|---|---|""")
    for name, scope, meas in P["streams"]:
        o.append("| **%s** | %s | %s |" % (esc(name), esc(scope), esc(meas)))

    o.append("""
### Current baseline position of each stream

| Stream | Start | Finish | Working days | Milestones |
|---|---|---|---:|---|""")
    stream_wbs = {"A — Underground shelter": ["2", "3", "4", "5", "6", "7", "12"],
                  "B — Sentry post": ["8"],
                  "C — Services and external works": ["9", "10", "11", "13"]}
    for label, tops in stream_wbs.items():
        sel = [t for t in tasks.values() if t.wbs.split(".")[0] in tops]
        es = min(t.es for t in sel)
        ef = max(t.ef for t in sel)
        mst = [m for m in D.MILESTONES if tasks[m[1]].wbs.split(".")[0] in tops]
        o.append("| **Stream %s** | %s | %s | %d | %s |"
                 % (label, S.dstr(es), S.dstr(ef), ef - es + 1,
                    ", ".join(m[0] for m in mst)))

    o.append("\n\n## Reporting cycle\n")
    o.append("| Frequency | Content |")
    o.append("|---|---|")
    for freq, content in P["cycle"]:
        o.append("| **%s** | %s |" % (freq, esc(content)))

    o.append("\n\n## Delay tracking\n")
    for p in P["delay"]:
        o.append(p + "\n")
    o.append("\n## Corrective action\n")
    for p in P["corrective"]:
        o.append(p + "\n")

    o.append("""
---

## Quantity-based progress — the measurement table

Physical progress against these quantities is what 'percent complete' means on this
project. They come straight from the BOQ.

| Work package | Measured on | Baseline quantity |
|---|---|---|
| Bulk excavation | m³ removed | 1 338 m³, of which 994 m³ in rock |
| Blinding and mat | m³ placed | 14.2 m³ M15 + 85.5 m³ M35 |
| Perimeter and protective walls | m³ placed / t fixed | 119.7 m³ M35 / 24.7 t |
| Pressure slab | m³ placed / t fixed | 112 m³ M35 / 20.5 t |
| Entry structures | m³ placed | 52.6 m³ M35 |
| Formwork | m² erected | 1 058 m² |
| Waterproofing | m² applied | 532 m² |
| Side backfill | m³ compacted and tested | 290 m³ |
| Engineered cover | m³ per layer | 206 m³ in six layers |
| **Sentry post frame** | **m³ placed** | **20.95 m³ M30** |
| **Sentry post brick masonry** | **m² and m³ built** | **64.19 m² / 12.20 m³** |
| Sentry post plaster | m² applied | 222.5 m² |
| Reinforcement, all works | t fixed | 73.65 t net of wastage |

## Milestone tracking

| Ref | Milestone | Baseline date | Float | Stream |
|---|---|---|---:|---|""")
    for mid, aid, name in D.MILESTONES:
        t = tasks[aid]
        top = t.wbs.split(".")[0]
        st = ("A" if top in stream_wbs["A — Underground shelter"] else
              "B" if top == "8" else
              "C" if top in stream_wbs["C — Services and external works"] else "Project")
        o.append("| `%s` | %s | %s | %d d | %s |"
                 % (mid, esc(name), S.CAL.day(t.es).strftime("%d %b %Y"), t.tf, st))

    o.append("""
## Float management

| Float band | Activities | Interpretation |
|---|---:|---|""")
    bands = [(0, 0, "Critical — any slip is a project slip"),
             (1, 10, "Near critical — flagged in every monthly report"),
             (11, 30, "Manageable — monitored"),
             (31, 90, "Comfortable"),
             (91, 10 ** 6, "Large — mostly procurement and the sentry post")]
    for lo, hi, desc in bands:
        n = sum(1 for t in tasks.values() if lo <= t.tf <= hi)
        label = "TF = 0" if hi == 0 else ("TF > 90" if hi > 10 ** 5
                                          else "TF %d–%d" % (lo, hi))
        o.append("| **%s** | %d | %s |" % (label, n, desc))

    o.append("""
An activity is flagged when its total float falls below **ten working days**,
whether or not it is critical. A chain quietly consuming float is the warning that
arrives before the delay does, and it is the only warning that arrives in time to be
useful.
""")
    write(os.path.join(DOCS, "WM_PROGRESS_MONITORING.md"), "\n".join(o))


# ===========================================================================
def doc_assumptions(tasks):
    o = [head("ASSUMPTIONS AND VERIFICATION REGISTER")]
    o.append("""Master rule M.6 governs this register: *never guess missing engineering
information; if something is marked UNRESOLVED or NOT AVAILABLE it stays that way
until the user supplies it.*

Nothing in this package resolves an item that the master leaves open, and nothing
downgrades or deletes an evidence tag. This register lists what the Works Management
package assumed in order to produce a programme and a bill, and what must be
confirmed before either is relied on.

---

## Part 1 — Items this package raised

| Ref | Item | Effect if wrong | Status |
|---|---|---|---|
| `WM-V1` | Sentry post ground-storey masonry height: the project's confirmed 2.600 m (master A.7.7) against the 2.750 m implied by +0.450 FFL and the +3.200 beam soffit | 15.2 m × 0.150 × 0.190 = 0.43 m³ of masonry, about 230 bricks | **OPEN** — 2.600 used |
| `WM-V2` | First-floor west wall: door D1 at Y 1000–1900 lies inside the vision panel at Y 1000–2200 on Rev F drawing 4 | Double deduction would understate the masonry by 1.9 m² | **OPEN** — the union is deducted once |
| `WM-V3` | Sentry post window and vision-panel heights are not stated on any drawing | 1200 assumed. Each 100 mm of height is 1.1 m² of masonry across the nine openings | **OPEN** |
| `WM-V4` | 190 mm modular brickwork inside the 200 mm structural zone | The alternative, 230 mm conventional brickwork, changes the confirmed 4000 × 5000 external envelope | **OPEN** — needs the designer's confirmation |
| `WM-V5` | Lintels over the sentry post openings — a **new** requirement created by SP-B1 | ~~No lintel design exists~~ — **lintel L1 is now designed, SP-B2, master A.4.8**. `SP-06` still measures the superseded provisional 200 × 150 section | **CLOSED by SP-B2**, 10 Sep 2026 |
| `WM-V6` | Sentry post seismic weight when RC infill becomes brick masonry | Brick at ~20 kN/m³ over 0.190 × 2.600 gives ~9.9 kN/m against the confirmed 13.000 kN/m, so the existing V<sub>b</sub> = 73.18 kN is **conservative**. A direction, not a verification | **OPEN** — referred to the structural discipline |
| `WM-V7` | Ballistic performance. Rev F calls the panels '200 RC BALLISTIC INFILL'; brick masonry does not give the same protection | A stated protective function is removed from a structure that is already declared not blast designed and expendable | **OPEN** — recorded so the consequence is visible |
| `WM-V8` | Mat measured gross, no deduction for the 1.5 × 1.5 sump opening | +1.35 m³. SC1's convention, kept | Conservative, declared |
| `WM-V9` | 1.000 m working space and vertical unbenched excavation faces | A slope-stability assessment of the soil zone above rockhead is required before excavation | **OPEN** |
| `WM-V10` | Bulking on rock excavation not applied | Loose volumes for haulage and stockpiling will be 40–60 % greater than the 1 114 m³ bank measure | Declared |
| `WM-V11` | Wall tie detail between the sentry post masonry and the columns | ~~No detail exists in the project~~ — **6 mm MS ties at every fifth course, SP-B2, master A.4.8** | **CLOSED by SP-B2**, 10 Sep 2026 |
| `WM-V12` | Opening heights for the W8 partition doors (900 gap confirmed, head height not stated) | 2100 assumed, consistent with every other door in the project | **OPEN**, minor |

## Part 2 — Programme assumptions

| Ref | Assumption |
|---|---|
| `WM-P1` | Project start Monday 2 November 2026, carried over from the supplied R0 schedule. A planning date, not a contractual one |
| `WM-P2` | All output rates are assumed. The quantities they are applied to are confirmed or derived and are traceable; the rates are not |
| `WM-P3` | Rock excavation programmed at the mean rockhead (-)1.750. At the shallow bound it rises to 1 043 m³ and the excavation lengthens by about a day |
| `WM-P4` | No blasting. Rock is removed by hydraulic breaker because the sentry post founds on the same rock within 10 m |
| `WM-P5` | Vendor lead times are assumed. They are the largest single risk in the programme and must be replaced by quoted times at tender |
| `WM-P6` | Six-day working week with five date-certain national holidays. Festival holidays are absorbed by the 10-day contingency activity `A14098` |
| `WM-P7` | Monsoon is handled by productivity allowances inside durations and by sequencing the deep excavation and external tanking outside June–September, not by a non-working calendar |
| `WM-P8` | The berm, access route and concealment works have no site plan behind them, so their durations are indicative |
| `WM-P9` | Cement at 400 kg/m³ for M35 against the IS 456 Table 5 minimum of 340. A trial mix to IS 10262 fixes the real content |

## Part 3 — Master items this package did NOT resolve

These remain exactly as the master leaves them.

| Ref | Item | Bearing on Works Management |
|---|---|---|
| `C16` | Roof / platform junction — 250 against 500 | Affects the covered entry stairwell roof (`A5105`), which carries float. Ruling needed before that activity |
| `C17` | Engineered cover — A.7.3 states 40.65 kPa but its own column sums to 39.15 | No effect on quantities: the six layers and their thicknesses are unambiguous and are what is measured |
| `C18` | Sump pit base — 400 from F.1 and the levels, 300 on sheet S-06 | 400 held, as the master holds it. Difference is 0.44 m³ |
| `C19` | Soak pit SK-01 is 2.3 % short of its own stated requirement | The percolation test may move the requirement by far more than 2.3 %. `Q-33` is a hold point before construction |
| `C20` | Sheet S-06 carries the Rev E stairwell catchment | Conservative. No Works Management effect |
| `C21` | CBRN filter duty 250 against 300 m³/h | **Must be ruled on before the filter trains are ordered.** `A1130` enquiry precedes `A1135` order for this reason |
| `U1` / `C9` | Sentry post V<sub>b</sub> 73.18 (STAAD) against 59.3 (hand) | Design uses 73.18. `WM-V6` adds a second reason to revisit it |
| `U2` · `U3` | Is a direct hit a requirement? · DBT yield | Client and military sign-off. No Works Management effect |
| `U8` | Roof projection and parapet 4.162 kN/m not independently reproducible | Parapet reinforcement is nominal `[A]` in the sentry post estimate |
| — | k<sub>s</sub> second bound (500 000 kN/m³) not run | Designer's item |
| — | Phase 3 not started: non-linear SDOF support rotation, shock propagation down the entry shaft, transient soil–structure interaction, blast-door vendor testing, sentry sheet S-09 | The programme delivers the structure that was designed. It does not validate the design |

## Part 4 — Information the project does not contain

These are not assumptions. They are gaps, and each one blocks something.

| Missing | Blocks | Needed by |
|---|---|---|
| **Electrical design package** — no circuit, cable, luminaire, DB or earth-electrode schedule | All electrical procurement and every electrical quantity | Before `A11025`, 23 Jul 27 |
| **Site plan / ground model** | Berm volume, access route, hardstanding, soakaway positions, several drainage runs | Before `A13010`, 10 Sep 27 |
| ~~**Sentry post lintel design**~~ | `A8140`, `A8155` | **SUPPLIED — lintel L1, SP-B2, master A.4.8, 10 Sep 2026. No longer a gap** |
| ~~**Sentry post wall tie detail**~~ | `A8135` | **SUPPLIED — 6 mm MS ties @ every 5th course, SP-B2, master A.4.8, 10 Sep 2026. No longer a gap** |
| **Blast door leaf, frame and anchorage details** | Frame cast-in at `A3105` | Vendor submittal, before 01 Apr 27 |
| **Blast valve sizes and sleeve details** | Sleeves cast in at `A9015` | Before the wall and slab pours |
| **Service-entry plate size at wall W2** | Cast-in at `A4060` | Before the pressure slab pour |
| **Ventilation and CBRN duct penetration schedule** | Cast-ins at `A4060` | Before the pressure slab pour |
| **EMP Zone 2 enclosure specification** | `A1150` enquiry | At mobilisation |
| **Armoured vision panel specification** | `A1165` enquiry | At mobilisation |
| **Finish product selections** (FN1 specifies performance only) | `A12025` onward | Before Aug 27 |
| **Sentry post ground-floor slab design** | `SC-08` | Before `A8060` |
| **W5 gas-tight door D-05** — the airlock has no scheduled clean-side exit | `A12065` | Before Sep 27 |

Every date above is computed from the programme. They are issued to the designer at
mobilisation, not requested when the activity is due to start.

---

## What this package did not do

* It did not run STAAD.Pro. STAAD.Pro is not available in this environment, and no
  analysis was performed. Reading a `.std` file is not running an analysis.
* It did not modify any drawing, model, calculation or design file. The only files
  changed outside the `WORKS MANAGEMENT` folder are `master/MASTER_PROJECT_STATE.md`
  (Part H revision record) and `master/QUICK_STATE.md`.
* It did not change the main staircase. The frozen geometry — 24 risers at
  170.8333, tread 280, three flights of eight, total rise 4100, flights 1200 wide,
  200 well, 2533 headroom — is unchanged and is reproduced in the programme as it
  stands.
* It did not resolve, downgrade or delete a single evidence tag from the master.
* It made only one design change, SP-B1, and made it because it was explicitly
  instructed.
""")
    write(os.path.join(DOCS, "WM_ASSUMPTIONS_AND_VERIFICATION_REGISTER.md"), "\n".join(o))


# ===========================================================================
def main():
    tasks, order, end, _ = S.summary()
    os.makedirs(DOCS, exist_ok=True)
    doc_wbs(tasks)
    doc_boq()
    doc_resources(tasks)
    doc_procurement(tasks)
    doc_qaqc(tasks)
    doc_safety_risk()
    doc_codes()
    doc_components()
    doc_methodology()
    doc_brick()
    doc_progress(tasks)
    doc_assumptions(tasks)
    print("documents written")


if __name__ == "__main__":
    main()
