"""
make_schedules.py  --  writes every bar bending / reinforcement schedule from
rebar_data.py.  The schedules and the drawings therefore CANNOT disagree: both
are generated from the same list.

Outputs (Structural CAD/Schedules/):
    BBS_MASTER.csv                  every mark, machine readable
    BBS_MASTER.md                   every mark, formatted
    BBS_<GROUP>.md                  one schedule per element group
    REINFORCEMENT_SUMMARY.md        totals by diameter, group and drawing
"""
import csv, os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rebar_data as R
import sc_proj as P
from rc_calc import bar_kg_per_m

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Schedules")
OUT = os.path.abspath(OUT)
os.makedirs(OUT, exist_ok=True)

HEAD = f"""<!-- GENERATED by Structural CAD/Scripts/make_schedules.py from
     Structural CAD/Scripts/rebar_data.py.  DO NOT EDIT BY HAND. -->

# {{title}}
## {P.PROJECT} — {P.LOCATION}
### Package revision **{P.PACKAGE_REV}** · structural revision {P.STRUCT_REV} · {P.PACKAGE_DATE}

**Material:** M35 concrete · **Fe500D** reinforcement to IS 1786:2008
**Cover:** 75 cast against blinding · 50 formed earth face · 40 internal · 30 stair shaft
**L_d tension 40 φ · lap 50 φ staggered (≤ 50 % spliced at any section)**
**Maximum bar spacing 150 mm both curtains — EMP requirement, stricter than IS 456 Cl. 26.3.3**

> **SENTRY POST EXCLUDED** — no sentry-post bar, quantity or weight appears in any schedule
> in this package.

**Quantity basis — declared, not assumed:**
* **PBR-1** cut length = Σ scheduled leg dimensions, **no bend deduction taken**; links add
  2 × 10 φ for 135° hooks. Conservative by ≈ 2 φ per 90° bend. Bend deductions to BS 8666
  Table 3 shall be applied by the fabricator on the approved schedule.
  **[ASSUMED — no bar-bending standard is in the workspace. IS 2502 is NOT held and NOT cited.]**
* **P-1** stock bar 12 000 mm; longer runs split into equal pieces with 50 φ laps added.
* **PBR-2** a 4-legged link @ s is scheduled as **two** closed links per node on an s × s grid;
  a 2-legged link @ s as **one**.
* **PBR-3** the stair void and the two escape openings are **deducted zone by zone**.
* Quantities are for **tender and estimating** and must be re-measured by the contractor on the
  approved bar bending schedule (QA/QC item R-8).

**Shape codes** — only the four unambiguous BS 8666 codes are used; anything else is coded
**99, "other — fully dimensioned sketch"**:

| Code | Description | Cut length |
|---|---|---|
| **00** | Straight | A |
| **11** | One 90° bend (L-bar) | A + B |
| **21** | Two 90° bends (U / crank) | A + B + C |
| **51** | Closed link, 135° hooks | 2(A + B) + 2 × 10 φ |
| **99** | Other — dimensioned sketch on the drawing | Σ legs |

---

"""

COLS = ["BAR MARK", "ELEMENT", "LOCATION", "DIA", "SHAPE", "SPACING",
        "A", "B", "C", "No.", "CUT LENGTH", "TOTAL LENGTH", "WEIGHT", "DRAWING", "REMARKS"]


def row(m):
    d = m["dims"] + ["", "", ""]
    return [m["mark"], m["element"], m["location"], f"T{m['phi']}", m["shape"],
            (str(m["spacing"]) if m["spacing"] else "—"),
            d[0], d[1], d[2], m["count"], round(m["cut"]),
            round(m["total_len"], 1), round(m["kg"], 1),
            " / ".join(m["drawings"]), m["remarks"]]


def md_table(marks):
    out = ["| " + " | ".join(COLS) + " |",
           "|" + "|".join(["---"] * len(COLS)) + "|"]
    for m in marks:
        r = row(m)
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def write_master():
    with open(os.path.join(OUT, "BBS_MASTER.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["# BAR BENDING SCHEDULE - MASTER. Generated from rebar_data.py."])
        w.writerow([f"# {P.PROJECT} - {P.LOCATION}. Package rev {P.PACKAGE_REV}, {P.PACKAGE_DATE}"])
        w.writerow(["# M35 / Fe500D. SENTRY POST EXCLUDED. Units mm, m, kg."])
        w.writerow(COLS)
        for m in R.MARKS:
            w.writerow(row(m))
        w.writerow([])
        w.writerow(["FABRIC"])
        w.writerow(["MARK", "ELEMENT", "LOCATION", "SPEC", "AREA m2", "DRAWING", "REMARKS"])
        for fb in R.FABRIC:
            w.writerow([fb["mark"], fb["element"], fb["location"], fb["spec"],
                        fb["area_m2"], " / ".join(fb["drawings"]), fb["remarks"]])
        w.writerow([])
        w.writerow(["TOTAL BAR REINFORCEMENT kg",
                    round(sum(m["kg"] for m in R.MARKS), 1)])

    body = [HEAD.format(title="BAR BENDING SCHEDULE — MASTER (ALL ELEMENTS)")]
    for g in dict.fromkeys(m["group"] for m in R.MARKS):
        body.append(f"## {g}\n")
        body.append(md_table([m for m in R.MARKS if m["group"] == g]))
        sub = sum(m["kg"] for m in R.MARKS if m["group"] == g)
        body.append(f"\n**{g} sub-total: {sub:,.1f} kg ({sub/1000:.3f} t)**\n")
    body.append("## FABRIC\n")
    body.append("| MARK | ELEMENT | LOCATION | SPEC | AREA m² | DRAWING | REMARKS |")
    body.append("|---|---|---|---|---|---|---|")
    for fb in R.FABRIC:
        body.append(f"| {fb['mark']} | {fb['element']} | {fb['location']} | {fb['spec']} | "
                    f"{fb['area_m2']} | {' / '.join(fb['drawings'])} | {fb['remarks']} |")
    tot = sum(m["kg"] for m in R.MARKS)
    body.append(f"\n---\n\n## **TOTAL BAR REINFORCEMENT: {tot:,.1f} kg = {tot/1000:.2f} tonnes**\n")
    body.append("*(fabric is scheduled by area, not included in the bar tonnage)*\n")
    with open(os.path.join(OUT, "BBS_MASTER.md"), "w") as f:
        f.write("\n".join(body))


def write_group_schedules():
    slug = {"FOUNDATIONS": "FOUNDATIONS", "WALLS": "WALLS", "ROOF SLAB": "ROOF_SLAB",
            "BEAM-TYPE ELEMENTS": "BEAM_TYPE", "MAIN STAIRCASE": "MAIN_STAIRCASE",
            "HEADHOUSE": "HEADHOUSE", "ENTRANCE / ENTRY STAIRWELL": "ENTRANCE"}
    for g, s in slug.items():
        marks = [m for m in R.MARKS if m["group"] == g]
        if not marks:
            continue
        body = [HEAD.format(title=f"BAR BENDING SCHEDULE — {g}"), md_table(marks)]
        sub = sum(m["kg"] for m in marks)
        body.append(f"\n**{g} TOTAL: {sub:,.1f} kg ({sub/1000:.3f} t)**\n")
        if g == "WALLS":
            body.append("\n> Fabric item **W18** (W8 partitions, A252 both faces) is scheduled "
                        "in `BBS_MASTER.md`. It is **non-structural** and no load path is "
                        "assumed through it.\n")
        with open(os.path.join(OUT, f"BBS_{s}.md"), "w") as f:
            f.write("\n".join(body))


def write_summary():
    tot = sum(m["kg"] for m in R.MARKS)
    b = [HEAD.format(title="REINFORCEMENT SUMMARY AND QUANTITIES")]
    b.append("## Summary by bar diameter\n")
    b.append("| Bar | Unit mass kg/m | No. of bars | Total length m | Weight kg | % of total |")
    b.append("|---|---|---|---|---|---|")
    for phi, (n, L, kg) in sorted(R.totals_by_dia().items()):
        b.append(f"| **T{phi}** | {bar_kg_per_m(phi):.3f} | {n:,} | {L:,.1f} | "
                 f"{kg:,.1f} | {100*kg/tot:.1f} % |")
    b.append(f"| | | **{sum(m['count'] for m in R.MARKS):,}** | "
             f"**{sum(m['total_len'] for m in R.MARKS):,.1f}** | **{tot:,.1f}** | 100 % |")

    b.append("\n## Summary by element group\n")
    b.append("| Element group | Weight kg | Weight t | % of total |")
    b.append("|---|---|---|---|")
    for g, kg in R.totals_by_group().items():
        b.append(f"| {g} | {kg:,.1f} | {kg/1000:.3f} | {100*kg/tot:.1f} % |")
    b.append(f"| **TOTAL** | **{tot:,.1f}** | **{tot/1000:.2f}** | **100 %** |")

    b.append("\n## Marks per drawing — cross-check\n")
    b.append("Every mark below appears on the listed drawing **and** has exactly one schedule "
             "entry. Verified by `Scripts/qa_crosscheck.py`.\n")
    b.append("| Drawing | Bar marks shown |")
    b.append("|---|---|")
    for dwg in R.all_drawings():
        ms = [m["mark"] for m in R.MARKS if dwg in m["drawings"]]
        ms += [f["mark"] for f in R.FABRIC if dwg in f["drawings"]]
        b.append(f"| **{dwg}** | {', '.join(sorted(ms))} |")

    b.append("\n## Approximate steel density — sanity check\n")
    vols = [("Mat 600", 22.0 * 6.2 * 0.6), ("Pressure slab 900 (net of openings)",
            22.0 * 6.2 * 0.9 - 2.8 * 3.16 * 0.9 - 2 * 3.1416 * 0.7 ** 2 * 0.9),
            ("Perimeter walls 600", 54.0 * 0.6 * 3.2),
            ("Walls W6 / W7 400", 2 * 5.0 * 0.4 * 3.2),
            ("Wall W5 200", 5.0 * 0.2 * 3.2),
            ("Headhouse walls 400 + roof 500", 19.6 * 0.4 * 2.4 + 4.8 * 5.8 * 0.5),
            ("Main staircase (waist + landings)", 3 * 2.296 * 1.2 * 0.2 + 2 * 2.8 * 1.2 * 0.2),
            ("Entry stairwell (walls, roof, raft, flight, landings)",
             2 * 6.8 * 0.25 * 2.9 + 6.8 * 2.0 * 0.25 + 6.8 * 2.0 * 0.3
             + 3.775 * 1.5 * 0.25 + 2 * 1.5 * 1.5 * 0.25)]
    V = sum(v for _, v in vols)
    b.append("| Element | Concrete m³ |")
    b.append("|---|---|")
    for nme, v in vols:
        b.append(f"| {nme} | {v:,.1f} |")
    b.append(f"| **TOTAL (in-scope, excluding blinding and the sump pit)** | **{V:,.1f}** |")
    b.append(f"\n**Average steel density ≈ {tot/V:.0f} kg/m³.** For a blast-hardened buried box "
             "whose bar spacing is set by the 150 mm EMP rule rather than by strength, and whose "
             "sections are thick (900 roof, 600 walls and mat), this is a plausible figure. "
             "It is a **sanity check, not a design check.**\n")

    b.append("\n## Items NOT quantified — declared\n")
    b.append("| Item | Why |\n|---|---|")
    b.append("| Blast valves ×5, sleeves and trimming | Sizes and sleeve details are on sheet "
             "S-06 and are **not in master Part B**. Not fabricated. Generic trimming rule on "
             "R-205 / R-303. **NOT DETERMINABLE** |")
    b.append("| Service-entry plate, W2 at X ≈ 11 800 | Plate size **[NOT AVAILABLE]** in Part B. "
             "**NOT DETERMINABLE** |")
    b.append("| Ventilation / CBRN duct penetrations | No penetration schedule exists in Part B. "
             "**NOT DETERMINABLE** |")
    b.append("| Blast-door leaf, frame and anchorage | Vendor item, **[NOT AVAILABLE]**. The "
             "cast-in frame is shown welded to the cage for EMP continuity; its anchorage is a "
             "vendor submittal |")
    b.append("| Burster slab in the engineered cover (M30, T12 @ 150 B/W) | Part of the cover "
             "build-up, **not a structural element of the shelter**. Excluded by scope |")
    b.append("| Waterstops, EMP straps, spacers, tying wire, chairs | Not reinforcement bars. "
             "To be measured separately |")
    b.append("| **Sentry post — everything** | **OUT OF SCOPE BY INSTRUCTION** |")

    with open(os.path.join(OUT, "REINFORCEMENT_SUMMARY.md"), "w") as f:
        f.write("\n".join(b))


if __name__ == "__main__":
    write_master()
    write_group_schedules()
    write_summary()
    tot = sum(m['kg'] for m in R.MARKS)
    print(f"schedules written to {OUT}")
    print(f"{len(R.MARKS)} marks, {tot:,.1f} kg = {tot/1000:.2f} t")
    for f in sorted(os.listdir(OUT)):
        print("   ", f)
